// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

#ifndef PROTOBUF_INCLUDED_base_2eproto
#define PROTOBUF_INCLUDED_base_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_base_2eproto 

namespace protobuf_base_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_base_2eproto
namespace dwarf {
class ComResponse;
class ComResponseDefaultTypeInternal;
extern ComResponseDefaultTypeInternal _ComResponse_default_instance_;
class WsPacket;
class WsPacketDefaultTypeInternal;
extern WsPacketDefaultTypeInternal _WsPacket_default_instance_;
}  // namespace dwarf
namespace google {
namespace protobuf {
template<> ::dwarf::ComResponse* Arena::CreateMaybeMessage<::dwarf::ComResponse>(Arena*);
template<> ::dwarf::WsPacket* Arena::CreateMaybeMessage<::dwarf::WsPacket>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace dwarf {

// ===================================================================

class WsPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.WsPacket) */ {
 public:
  WsPacket();
  virtual ~WsPacket();

  WsPacket(const WsPacket& from);

  inline WsPacket& operator=(const WsPacket& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WsPacket(WsPacket&& from) noexcept
    : WsPacket() {
    *this = ::std::move(from);
  }

  inline WsPacket& operator=(WsPacket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const WsPacket& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WsPacket* internal_default_instance() {
    return reinterpret_cast<const WsPacket*>(
               &_WsPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(WsPacket* other);
  friend void swap(WsPacket& a, WsPacket& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WsPacket* New() const final {
    return CreateMaybeMessage<WsPacket>(NULL);
  }

  WsPacket* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WsPacket>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WsPacket& from);
  void MergeFrom(const WsPacket& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WsPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes data = 7;
  void clear_data();
  static const int kDataFieldNumber = 7;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // string client_id = 8;
  void clear_client_id();
  static const int kClientIdFieldNumber = 8;
  const ::std::string& client_id() const;
  void set_client_id(const ::std::string& value);
  #if LANG_CXX11
  void set_client_id(::std::string&& value);
  #endif
  void set_client_id(const char* value);
  void set_client_id(const char* value, size_t size);
  ::std::string* mutable_client_id();
  ::std::string* release_client_id();
  void set_allocated_client_id(::std::string* client_id);

  // uint32 major_version = 1;
  void clear_major_version();
  static const int kMajorVersionFieldNumber = 1;
  ::google::protobuf::uint32 major_version() const;
  void set_major_version(::google::protobuf::uint32 value);

  // uint32 minor_version = 2;
  void clear_minor_version();
  static const int kMinorVersionFieldNumber = 2;
  ::google::protobuf::uint32 minor_version() const;
  void set_minor_version(::google::protobuf::uint32 value);

  // uint32 device_id = 3;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 3;
  ::google::protobuf::uint32 device_id() const;
  void set_device_id(::google::protobuf::uint32 value);

  // uint32 module_id = 4;
  void clear_module_id();
  static const int kModuleIdFieldNumber = 4;
  ::google::protobuf::uint32 module_id() const;
  void set_module_id(::google::protobuf::uint32 value);

  // uint32 cmd = 5;
  void clear_cmd();
  static const int kCmdFieldNumber = 5;
  ::google::protobuf::uint32 cmd() const;
  void set_cmd(::google::protobuf::uint32 value);

  // uint32 type = 6;
  void clear_type();
  static const int kTypeFieldNumber = 6;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:dwarf.WsPacket)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::internal::ArenaStringPtr client_id_;
  ::google::protobuf::uint32 major_version_;
  ::google::protobuf::uint32 minor_version_;
  ::google::protobuf::uint32 device_id_;
  ::google::protobuf::uint32 module_id_;
  ::google::protobuf::uint32 cmd_;
  ::google::protobuf::uint32 type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ComResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ComResponse) */ {
 public:
  ComResponse();
  virtual ~ComResponse();

  ComResponse(const ComResponse& from);

  inline ComResponse& operator=(const ComResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ComResponse(ComResponse&& from) noexcept
    : ComResponse() {
    *this = ::std::move(from);
  }

  inline ComResponse& operator=(ComResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ComResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ComResponse* internal_default_instance() {
    return reinterpret_cast<const ComResponse*>(
               &_ComResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ComResponse* other);
  friend void swap(ComResponse& a, ComResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ComResponse* New() const final {
    return CreateMaybeMessage<ComResponse>(NULL);
  }

  ComResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ComResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ComResponse& from);
  void MergeFrom(const ComResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ComResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ComResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_base_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WsPacket

// uint32 major_version = 1;
inline void WsPacket::clear_major_version() {
  major_version_ = 0u;
}
inline ::google::protobuf::uint32 WsPacket::major_version() const {
  // @@protoc_insertion_point(field_get:dwarf.WsPacket.major_version)
  return major_version_;
}
inline void WsPacket::set_major_version(::google::protobuf::uint32 value) {
  
  major_version_ = value;
  // @@protoc_insertion_point(field_set:dwarf.WsPacket.major_version)
}

// uint32 minor_version = 2;
inline void WsPacket::clear_minor_version() {
  minor_version_ = 0u;
}
inline ::google::protobuf::uint32 WsPacket::minor_version() const {
  // @@protoc_insertion_point(field_get:dwarf.WsPacket.minor_version)
  return minor_version_;
}
inline void WsPacket::set_minor_version(::google::protobuf::uint32 value) {
  
  minor_version_ = value;
  // @@protoc_insertion_point(field_set:dwarf.WsPacket.minor_version)
}

// uint32 device_id = 3;
inline void WsPacket::clear_device_id() {
  device_id_ = 0u;
}
inline ::google::protobuf::uint32 WsPacket::device_id() const {
  // @@protoc_insertion_point(field_get:dwarf.WsPacket.device_id)
  return device_id_;
}
inline void WsPacket::set_device_id(::google::protobuf::uint32 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:dwarf.WsPacket.device_id)
}

// uint32 module_id = 4;
inline void WsPacket::clear_module_id() {
  module_id_ = 0u;
}
inline ::google::protobuf::uint32 WsPacket::module_id() const {
  // @@protoc_insertion_point(field_get:dwarf.WsPacket.module_id)
  return module_id_;
}
inline void WsPacket::set_module_id(::google::protobuf::uint32 value) {
  
  module_id_ = value;
  // @@protoc_insertion_point(field_set:dwarf.WsPacket.module_id)
}

// uint32 cmd = 5;
inline void WsPacket::clear_cmd() {
  cmd_ = 0u;
}
inline ::google::protobuf::uint32 WsPacket::cmd() const {
  // @@protoc_insertion_point(field_get:dwarf.WsPacket.cmd)
  return cmd_;
}
inline void WsPacket::set_cmd(::google::protobuf::uint32 value) {
  
  cmd_ = value;
  // @@protoc_insertion_point(field_set:dwarf.WsPacket.cmd)
}

// uint32 type = 6;
inline void WsPacket::clear_type() {
  type_ = 0u;
}
inline ::google::protobuf::uint32 WsPacket::type() const {
  // @@protoc_insertion_point(field_get:dwarf.WsPacket.type)
  return type_;
}
inline void WsPacket::set_type(::google::protobuf::uint32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:dwarf.WsPacket.type)
}

// bytes data = 7;
inline void WsPacket::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& WsPacket::data() const {
  // @@protoc_insertion_point(field_get:dwarf.WsPacket.data)
  return data_.GetNoArena();
}
inline void WsPacket::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dwarf.WsPacket.data)
}
#if LANG_CXX11
inline void WsPacket::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dwarf.WsPacket.data)
}
#endif
inline void WsPacket::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dwarf.WsPacket.data)
}
inline void WsPacket::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dwarf.WsPacket.data)
}
inline ::std::string* WsPacket::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:dwarf.WsPacket.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WsPacket::release_data() {
  // @@protoc_insertion_point(field_release:dwarf.WsPacket.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WsPacket::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:dwarf.WsPacket.data)
}

// string client_id = 8;
inline void WsPacket::clear_client_id() {
  client_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& WsPacket::client_id() const {
  // @@protoc_insertion_point(field_get:dwarf.WsPacket.client_id)
  return client_id_.GetNoArena();
}
inline void WsPacket::set_client_id(const ::std::string& value) {
  
  client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dwarf.WsPacket.client_id)
}
#if LANG_CXX11
inline void WsPacket::set_client_id(::std::string&& value) {
  
  client_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dwarf.WsPacket.client_id)
}
#endif
inline void WsPacket::set_client_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dwarf.WsPacket.client_id)
}
inline void WsPacket::set_client_id(const char* value, size_t size) {
  
  client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dwarf.WsPacket.client_id)
}
inline ::std::string* WsPacket::mutable_client_id() {
  
  // @@protoc_insertion_point(field_mutable:dwarf.WsPacket.client_id)
  return client_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* WsPacket::release_client_id() {
  // @@protoc_insertion_point(field_release:dwarf.WsPacket.client_id)
  
  return client_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void WsPacket::set_allocated_client_id(::std::string* client_id) {
  if (client_id != NULL) {
    
  } else {
    
  }
  client_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), client_id);
  // @@protoc_insertion_point(field_set_allocated:dwarf.WsPacket.client_id)
}

// -------------------------------------------------------------------

// ComResponse

// int32 code = 1;
inline void ComResponse::clear_code() {
  code_ = 0;
}
inline ::google::protobuf::int32 ComResponse::code() const {
  // @@protoc_insertion_point(field_get:dwarf.ComResponse.code)
  return code_;
}
inline void ComResponse::set_code(::google::protobuf::int32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ComResponse.code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dwarf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_base_2eproto
