// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: focus.proto

#ifndef PROTOBUF_INCLUDED_focus_2eproto
#define PROTOBUF_INCLUDED_focus_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_focus_2eproto 

namespace protobuf_focus_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_focus_2eproto
namespace dwarf {
class ReqAstroAutoFocus;
class ReqAstroAutoFocusDefaultTypeInternal;
extern ReqAstroAutoFocusDefaultTypeInternal _ReqAstroAutoFocus_default_instance_;
class ReqManualSingleStepFocus;
class ReqManualSingleStepFocusDefaultTypeInternal;
extern ReqManualSingleStepFocusDefaultTypeInternal _ReqManualSingleStepFocus_default_instance_;
class ReqNormalAutoFocus;
class ReqNormalAutoFocusDefaultTypeInternal;
extern ReqNormalAutoFocusDefaultTypeInternal _ReqNormalAutoFocus_default_instance_;
class ReqStartManualContinuFocus;
class ReqStartManualContinuFocusDefaultTypeInternal;
extern ReqStartManualContinuFocusDefaultTypeInternal _ReqStartManualContinuFocus_default_instance_;
class ReqStopAstroAutoFocus;
class ReqStopAstroAutoFocusDefaultTypeInternal;
extern ReqStopAstroAutoFocusDefaultTypeInternal _ReqStopAstroAutoFocus_default_instance_;
class ReqStopManualContinuFocus;
class ReqStopManualContinuFocusDefaultTypeInternal;
extern ReqStopManualContinuFocusDefaultTypeInternal _ReqStopManualContinuFocus_default_instance_;
}  // namespace dwarf
namespace google {
namespace protobuf {
template<> ::dwarf::ReqAstroAutoFocus* Arena::CreateMaybeMessage<::dwarf::ReqAstroAutoFocus>(Arena*);
template<> ::dwarf::ReqManualSingleStepFocus* Arena::CreateMaybeMessage<::dwarf::ReqManualSingleStepFocus>(Arena*);
template<> ::dwarf::ReqNormalAutoFocus* Arena::CreateMaybeMessage<::dwarf::ReqNormalAutoFocus>(Arena*);
template<> ::dwarf::ReqStartManualContinuFocus* Arena::CreateMaybeMessage<::dwarf::ReqStartManualContinuFocus>(Arena*);
template<> ::dwarf::ReqStopAstroAutoFocus* Arena::CreateMaybeMessage<::dwarf::ReqStopAstroAutoFocus>(Arena*);
template<> ::dwarf::ReqStopManualContinuFocus* Arena::CreateMaybeMessage<::dwarf::ReqStopManualContinuFocus>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace dwarf {

// ===================================================================

class ReqNormalAutoFocus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqNormalAutoFocus) */ {
 public:
  ReqNormalAutoFocus();
  virtual ~ReqNormalAutoFocus();

  ReqNormalAutoFocus(const ReqNormalAutoFocus& from);

  inline ReqNormalAutoFocus& operator=(const ReqNormalAutoFocus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqNormalAutoFocus(ReqNormalAutoFocus&& from) noexcept
    : ReqNormalAutoFocus() {
    *this = ::std::move(from);
  }

  inline ReqNormalAutoFocus& operator=(ReqNormalAutoFocus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqNormalAutoFocus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqNormalAutoFocus* internal_default_instance() {
    return reinterpret_cast<const ReqNormalAutoFocus*>(
               &_ReqNormalAutoFocus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ReqNormalAutoFocus* other);
  friend void swap(ReqNormalAutoFocus& a, ReqNormalAutoFocus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqNormalAutoFocus* New() const final {
    return CreateMaybeMessage<ReqNormalAutoFocus>(NULL);
  }

  ReqNormalAutoFocus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqNormalAutoFocus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqNormalAutoFocus& from);
  void MergeFrom(const ReqNormalAutoFocus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqNormalAutoFocus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 mode = 1;
  void clear_mode();
  static const int kModeFieldNumber = 1;
  ::google::protobuf::uint32 mode() const;
  void set_mode(::google::protobuf::uint32 value);

  // uint32 center_x = 2;
  void clear_center_x();
  static const int kCenterXFieldNumber = 2;
  ::google::protobuf::uint32 center_x() const;
  void set_center_x(::google::protobuf::uint32 value);

  // uint32 center_y = 3;
  void clear_center_y();
  static const int kCenterYFieldNumber = 3;
  ::google::protobuf::uint32 center_y() const;
  void set_center_y(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ReqNormalAutoFocus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 mode_;
  ::google::protobuf::uint32 center_x_;
  ::google::protobuf::uint32 center_y_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_focus_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqAstroAutoFocus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqAstroAutoFocus) */ {
 public:
  ReqAstroAutoFocus();
  virtual ~ReqAstroAutoFocus();

  ReqAstroAutoFocus(const ReqAstroAutoFocus& from);

  inline ReqAstroAutoFocus& operator=(const ReqAstroAutoFocus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqAstroAutoFocus(ReqAstroAutoFocus&& from) noexcept
    : ReqAstroAutoFocus() {
    *this = ::std::move(from);
  }

  inline ReqAstroAutoFocus& operator=(ReqAstroAutoFocus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqAstroAutoFocus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqAstroAutoFocus* internal_default_instance() {
    return reinterpret_cast<const ReqAstroAutoFocus*>(
               &_ReqAstroAutoFocus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ReqAstroAutoFocus* other);
  friend void swap(ReqAstroAutoFocus& a, ReqAstroAutoFocus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqAstroAutoFocus* New() const final {
    return CreateMaybeMessage<ReqAstroAutoFocus>(NULL);
  }

  ReqAstroAutoFocus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqAstroAutoFocus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqAstroAutoFocus& from);
  void MergeFrom(const ReqAstroAutoFocus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqAstroAutoFocus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 mode = 1;
  void clear_mode();
  static const int kModeFieldNumber = 1;
  ::google::protobuf::uint32 mode() const;
  void set_mode(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ReqAstroAutoFocus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 mode_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_focus_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqManualSingleStepFocus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqManualSingleStepFocus) */ {
 public:
  ReqManualSingleStepFocus();
  virtual ~ReqManualSingleStepFocus();

  ReqManualSingleStepFocus(const ReqManualSingleStepFocus& from);

  inline ReqManualSingleStepFocus& operator=(const ReqManualSingleStepFocus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqManualSingleStepFocus(ReqManualSingleStepFocus&& from) noexcept
    : ReqManualSingleStepFocus() {
    *this = ::std::move(from);
  }

  inline ReqManualSingleStepFocus& operator=(ReqManualSingleStepFocus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqManualSingleStepFocus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqManualSingleStepFocus* internal_default_instance() {
    return reinterpret_cast<const ReqManualSingleStepFocus*>(
               &_ReqManualSingleStepFocus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ReqManualSingleStepFocus* other);
  friend void swap(ReqManualSingleStepFocus& a, ReqManualSingleStepFocus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqManualSingleStepFocus* New() const final {
    return CreateMaybeMessage<ReqManualSingleStepFocus>(NULL);
  }

  ReqManualSingleStepFocus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqManualSingleStepFocus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqManualSingleStepFocus& from);
  void MergeFrom(const ReqManualSingleStepFocus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqManualSingleStepFocus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 direction = 1;
  void clear_direction();
  static const int kDirectionFieldNumber = 1;
  ::google::protobuf::uint32 direction() const;
  void set_direction(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ReqManualSingleStepFocus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 direction_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_focus_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqStartManualContinuFocus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqStartManualContinuFocus) */ {
 public:
  ReqStartManualContinuFocus();
  virtual ~ReqStartManualContinuFocus();

  ReqStartManualContinuFocus(const ReqStartManualContinuFocus& from);

  inline ReqStartManualContinuFocus& operator=(const ReqStartManualContinuFocus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqStartManualContinuFocus(ReqStartManualContinuFocus&& from) noexcept
    : ReqStartManualContinuFocus() {
    *this = ::std::move(from);
  }

  inline ReqStartManualContinuFocus& operator=(ReqStartManualContinuFocus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqStartManualContinuFocus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqStartManualContinuFocus* internal_default_instance() {
    return reinterpret_cast<const ReqStartManualContinuFocus*>(
               &_ReqStartManualContinuFocus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ReqStartManualContinuFocus* other);
  friend void swap(ReqStartManualContinuFocus& a, ReqStartManualContinuFocus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqStartManualContinuFocus* New() const final {
    return CreateMaybeMessage<ReqStartManualContinuFocus>(NULL);
  }

  ReqStartManualContinuFocus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqStartManualContinuFocus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqStartManualContinuFocus& from);
  void MergeFrom(const ReqStartManualContinuFocus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqStartManualContinuFocus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 direction = 1;
  void clear_direction();
  static const int kDirectionFieldNumber = 1;
  ::google::protobuf::uint32 direction() const;
  void set_direction(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ReqStartManualContinuFocus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 direction_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_focus_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqStopManualContinuFocus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqStopManualContinuFocus) */ {
 public:
  ReqStopManualContinuFocus();
  virtual ~ReqStopManualContinuFocus();

  ReqStopManualContinuFocus(const ReqStopManualContinuFocus& from);

  inline ReqStopManualContinuFocus& operator=(const ReqStopManualContinuFocus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqStopManualContinuFocus(ReqStopManualContinuFocus&& from) noexcept
    : ReqStopManualContinuFocus() {
    *this = ::std::move(from);
  }

  inline ReqStopManualContinuFocus& operator=(ReqStopManualContinuFocus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqStopManualContinuFocus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqStopManualContinuFocus* internal_default_instance() {
    return reinterpret_cast<const ReqStopManualContinuFocus*>(
               &_ReqStopManualContinuFocus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ReqStopManualContinuFocus* other);
  friend void swap(ReqStopManualContinuFocus& a, ReqStopManualContinuFocus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqStopManualContinuFocus* New() const final {
    return CreateMaybeMessage<ReqStopManualContinuFocus>(NULL);
  }

  ReqStopManualContinuFocus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqStopManualContinuFocus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqStopManualContinuFocus& from);
  void MergeFrom(const ReqStopManualContinuFocus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqStopManualContinuFocus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:dwarf.ReqStopManualContinuFocus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_focus_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqStopAstroAutoFocus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqStopAstroAutoFocus) */ {
 public:
  ReqStopAstroAutoFocus();
  virtual ~ReqStopAstroAutoFocus();

  ReqStopAstroAutoFocus(const ReqStopAstroAutoFocus& from);

  inline ReqStopAstroAutoFocus& operator=(const ReqStopAstroAutoFocus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqStopAstroAutoFocus(ReqStopAstroAutoFocus&& from) noexcept
    : ReqStopAstroAutoFocus() {
    *this = ::std::move(from);
  }

  inline ReqStopAstroAutoFocus& operator=(ReqStopAstroAutoFocus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqStopAstroAutoFocus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqStopAstroAutoFocus* internal_default_instance() {
    return reinterpret_cast<const ReqStopAstroAutoFocus*>(
               &_ReqStopAstroAutoFocus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ReqStopAstroAutoFocus* other);
  friend void swap(ReqStopAstroAutoFocus& a, ReqStopAstroAutoFocus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqStopAstroAutoFocus* New() const final {
    return CreateMaybeMessage<ReqStopAstroAutoFocus>(NULL);
  }

  ReqStopAstroAutoFocus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqStopAstroAutoFocus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqStopAstroAutoFocus& from);
  void MergeFrom(const ReqStopAstroAutoFocus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqStopAstroAutoFocus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:dwarf.ReqStopAstroAutoFocus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_focus_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReqNormalAutoFocus

// uint32 mode = 1;
inline void ReqNormalAutoFocus::clear_mode() {
  mode_ = 0u;
}
inline ::google::protobuf::uint32 ReqNormalAutoFocus::mode() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqNormalAutoFocus.mode)
  return mode_;
}
inline void ReqNormalAutoFocus::set_mode(::google::protobuf::uint32 value) {
  
  mode_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqNormalAutoFocus.mode)
}

// uint32 center_x = 2;
inline void ReqNormalAutoFocus::clear_center_x() {
  center_x_ = 0u;
}
inline ::google::protobuf::uint32 ReqNormalAutoFocus::center_x() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqNormalAutoFocus.center_x)
  return center_x_;
}
inline void ReqNormalAutoFocus::set_center_x(::google::protobuf::uint32 value) {
  
  center_x_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqNormalAutoFocus.center_x)
}

// uint32 center_y = 3;
inline void ReqNormalAutoFocus::clear_center_y() {
  center_y_ = 0u;
}
inline ::google::protobuf::uint32 ReqNormalAutoFocus::center_y() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqNormalAutoFocus.center_y)
  return center_y_;
}
inline void ReqNormalAutoFocus::set_center_y(::google::protobuf::uint32 value) {
  
  center_y_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqNormalAutoFocus.center_y)
}

// -------------------------------------------------------------------

// ReqAstroAutoFocus

// uint32 mode = 1;
inline void ReqAstroAutoFocus::clear_mode() {
  mode_ = 0u;
}
inline ::google::protobuf::uint32 ReqAstroAutoFocus::mode() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqAstroAutoFocus.mode)
  return mode_;
}
inline void ReqAstroAutoFocus::set_mode(::google::protobuf::uint32 value) {
  
  mode_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqAstroAutoFocus.mode)
}

// -------------------------------------------------------------------

// ReqManualSingleStepFocus

// uint32 direction = 1;
inline void ReqManualSingleStepFocus::clear_direction() {
  direction_ = 0u;
}
inline ::google::protobuf::uint32 ReqManualSingleStepFocus::direction() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqManualSingleStepFocus.direction)
  return direction_;
}
inline void ReqManualSingleStepFocus::set_direction(::google::protobuf::uint32 value) {
  
  direction_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqManualSingleStepFocus.direction)
}

// -------------------------------------------------------------------

// ReqStartManualContinuFocus

// uint32 direction = 1;
inline void ReqStartManualContinuFocus::clear_direction() {
  direction_ = 0u;
}
inline ::google::protobuf::uint32 ReqStartManualContinuFocus::direction() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqStartManualContinuFocus.direction)
  return direction_;
}
inline void ReqStartManualContinuFocus::set_direction(::google::protobuf::uint32 value) {
  
  direction_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqStartManualContinuFocus.direction)
}

// -------------------------------------------------------------------

// ReqStopManualContinuFocus

// -------------------------------------------------------------------

// ReqStopAstroAutoFocus

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dwarf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_focus_2eproto
