// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motor.proto

#include "motor.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace dwarf {
class ReqMotorRunDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqMotorRun>
      _instance;
} _ReqMotorRun_default_instance_;
class ResMotorDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResMotor>
      _instance;
} _ResMotor_default_instance_;
class ReqMotorStopDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqMotorStop>
      _instance;
} _ReqMotorStop_default_instance_;
class ReqMotorServiceJoystickDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqMotorServiceJoystick>
      _instance;
} _ReqMotorServiceJoystick_default_instance_;
class ReqMotorServiceJoystickFixedAngleDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqMotorServiceJoystickFixedAngle>
      _instance;
} _ReqMotorServiceJoystickFixedAngle_default_instance_;
class ReqMotorServiceJoystickStopDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqMotorServiceJoystickStop>
      _instance;
} _ReqMotorServiceJoystickStop_default_instance_;
class ReqDualCameraLinkageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqDualCameraLinkage>
      _instance;
} _ReqDualCameraLinkage_default_instance_;
}  // namespace dwarf
namespace protobuf_motor_2eproto {
static void InitDefaultsReqMotorRun() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqMotorRun_default_instance_;
    new (ptr) ::dwarf::ReqMotorRun();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqMotorRun::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqMotorRun =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqMotorRun}, {}};

static void InitDefaultsResMotor() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ResMotor_default_instance_;
    new (ptr) ::dwarf::ResMotor();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ResMotor::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ResMotor =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsResMotor}, {}};

static void InitDefaultsReqMotorStop() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqMotorStop_default_instance_;
    new (ptr) ::dwarf::ReqMotorStop();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqMotorStop::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqMotorStop =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqMotorStop}, {}};

static void InitDefaultsReqMotorServiceJoystick() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqMotorServiceJoystick_default_instance_;
    new (ptr) ::dwarf::ReqMotorServiceJoystick();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqMotorServiceJoystick::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqMotorServiceJoystick =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqMotorServiceJoystick}, {}};

static void InitDefaultsReqMotorServiceJoystickFixedAngle() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqMotorServiceJoystickFixedAngle_default_instance_;
    new (ptr) ::dwarf::ReqMotorServiceJoystickFixedAngle();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqMotorServiceJoystickFixedAngle::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqMotorServiceJoystickFixedAngle =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqMotorServiceJoystickFixedAngle}, {}};

static void InitDefaultsReqMotorServiceJoystickStop() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqMotorServiceJoystickStop_default_instance_;
    new (ptr) ::dwarf::ReqMotorServiceJoystickStop();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqMotorServiceJoystickStop::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqMotorServiceJoystickStop =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqMotorServiceJoystickStop}, {}};

static void InitDefaultsReqDualCameraLinkage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqDualCameraLinkage_default_instance_;
    new (ptr) ::dwarf::ReqDualCameraLinkage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqDualCameraLinkage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqDualCameraLinkage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqDualCameraLinkage}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ReqMotorRun.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ResMotor.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqMotorStop.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqMotorServiceJoystick.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqMotorServiceJoystickFixedAngle.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqMotorServiceJoystickStop.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqDualCameraLinkage.base);
}

::google::protobuf::Metadata file_level_metadata[7];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorRun, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorRun, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorRun, speed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorRun, direction_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorRun, speed_ramping_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorRun, resolution_level_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ResMotor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ResMotor, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ResMotor, code_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorStop, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorStop, id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorServiceJoystick, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorServiceJoystick, vector_angle_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorServiceJoystick, vector_length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorServiceJoystick, speed_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorServiceJoystickFixedAngle, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorServiceJoystickFixedAngle, vector_angle_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorServiceJoystickFixedAngle, vector_length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorServiceJoystickFixedAngle, speed_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMotorServiceJoystickStop, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqDualCameraLinkage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqDualCameraLinkage, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqDualCameraLinkage, y_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::dwarf::ReqMotorRun)},
  { 10, -1, sizeof(::dwarf::ResMotor)},
  { 17, -1, sizeof(::dwarf::ReqMotorStop)},
  { 23, -1, sizeof(::dwarf::ReqMotorServiceJoystick)},
  { 31, -1, sizeof(::dwarf::ReqMotorServiceJoystickFixedAngle)},
  { 39, -1, sizeof(::dwarf::ReqMotorServiceJoystickStop)},
  { 44, -1, sizeof(::dwarf::ReqDualCameraLinkage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqMotorRun_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ResMotor_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqMotorStop_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqMotorServiceJoystick_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqMotorServiceJoystickFixedAngle_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqMotorServiceJoystickStop_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqDualCameraLinkage_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "motor.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 7);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013motor.proto\022\005dwarf\"l\n\013ReqMotorRun\022\n\n\002i"
      "d\030\001 \001(\005\022\r\n\005speed\030\002 \001(\001\022\021\n\tdirection\030\003 \001("
      "\010\022\025\n\rspeed_ramping\030\004 \001(\005\022\030\n\020resolution_l"
      "evel\030\005 \001(\005\"$\n\010ResMotor\022\n\n\002id\030\001 \001(\005\022\014\n\004co"
      "de\030\002 \001(\005\"\032\n\014ReqMotorStop\022\n\n\002id\030\001 \001(\005\"U\n\027"
      "ReqMotorServiceJoystick\022\024\n\014vector_angle\030"
      "\001 \001(\001\022\025\n\rvector_length\030\002 \001(\001\022\r\n\005speed\030\003 "
      "\001(\001\"_\n!ReqMotorServiceJoystickFixedAngle"
      "\022\024\n\014vector_angle\030\001 \001(\001\022\025\n\rvector_length\030"
      "\002 \001(\001\022\r\n\005speed\030\003 \001(\001\"\035\n\033ReqMotorServiceJ"
      "oystickStop\",\n\024ReqDualCameraLinkage\022\t\n\001x"
      "\030\001 \001(\005\022\t\n\001y\030\002 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 465);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "motor.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_motor_2eproto
namespace dwarf {

// ===================================================================

void ReqMotorRun::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqMotorRun::kIdFieldNumber;
const int ReqMotorRun::kSpeedFieldNumber;
const int ReqMotorRun::kDirectionFieldNumber;
const int ReqMotorRun::kSpeedRampingFieldNumber;
const int ReqMotorRun::kResolutionLevelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqMotorRun::ReqMotorRun()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_motor_2eproto::scc_info_ReqMotorRun.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqMotorRun)
}
ReqMotorRun::ReqMotorRun(const ReqMotorRun& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&speed_, &from.speed_,
    static_cast<size_t>(reinterpret_cast<char*>(&resolution_level_) -
    reinterpret_cast<char*>(&speed_)) + sizeof(resolution_level_));
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqMotorRun)
}

void ReqMotorRun::SharedCtor() {
  ::memset(&speed_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&resolution_level_) -
      reinterpret_cast<char*>(&speed_)) + sizeof(resolution_level_));
}

ReqMotorRun::~ReqMotorRun() {
  // @@protoc_insertion_point(destructor:dwarf.ReqMotorRun)
  SharedDtor();
}

void ReqMotorRun::SharedDtor() {
}

void ReqMotorRun::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqMotorRun::descriptor() {
  ::protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqMotorRun& ReqMotorRun::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_motor_2eproto::scc_info_ReqMotorRun.base);
  return *internal_default_instance();
}


void ReqMotorRun::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqMotorRun)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&speed_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&resolution_level_) -
      reinterpret_cast<char*>(&speed_)) + sizeof(resolution_level_));
  _internal_metadata_.Clear();
}

bool ReqMotorRun::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqMotorRun)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double speed = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &speed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool direction = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &direction_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 speed_ramping = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &speed_ramping_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 resolution_level = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &resolution_level_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqMotorRun)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqMotorRun)
  return false;
#undef DO_
}

void ReqMotorRun::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqMotorRun)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // double speed = 2;
  if (this->speed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->speed(), output);
  }

  // bool direction = 3;
  if (this->direction() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->direction(), output);
  }

  // int32 speed_ramping = 4;
  if (this->speed_ramping() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->speed_ramping(), output);
  }

  // int32 resolution_level = 5;
  if (this->resolution_level() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->resolution_level(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqMotorRun)
}

::google::protobuf::uint8* ReqMotorRun::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqMotorRun)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // double speed = 2;
  if (this->speed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->speed(), target);
  }

  // bool direction = 3;
  if (this->direction() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->direction(), target);
  }

  // int32 speed_ramping = 4;
  if (this->speed_ramping() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->speed_ramping(), target);
  }

  // int32 resolution_level = 5;
  if (this->resolution_level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->resolution_level(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqMotorRun)
  return target;
}

size_t ReqMotorRun::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqMotorRun)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double speed = 2;
  if (this->speed() != 0) {
    total_size += 1 + 8;
  }

  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  // bool direction = 3;
  if (this->direction() != 0) {
    total_size += 1 + 1;
  }

  // int32 speed_ramping = 4;
  if (this->speed_ramping() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->speed_ramping());
  }

  // int32 resolution_level = 5;
  if (this->resolution_level() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->resolution_level());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqMotorRun::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqMotorRun)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqMotorRun* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqMotorRun>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqMotorRun)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqMotorRun)
    MergeFrom(*source);
  }
}

void ReqMotorRun::MergeFrom(const ReqMotorRun& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqMotorRun)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.speed() != 0) {
    set_speed(from.speed());
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.direction() != 0) {
    set_direction(from.direction());
  }
  if (from.speed_ramping() != 0) {
    set_speed_ramping(from.speed_ramping());
  }
  if (from.resolution_level() != 0) {
    set_resolution_level(from.resolution_level());
  }
}

void ReqMotorRun::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqMotorRun)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqMotorRun::CopyFrom(const ReqMotorRun& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqMotorRun)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqMotorRun::IsInitialized() const {
  return true;
}

void ReqMotorRun::Swap(ReqMotorRun* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqMotorRun::InternalSwap(ReqMotorRun* other) {
  using std::swap;
  swap(speed_, other->speed_);
  swap(id_, other->id_);
  swap(direction_, other->direction_);
  swap(speed_ramping_, other->speed_ramping_);
  swap(resolution_level_, other->resolution_level_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqMotorRun::GetMetadata() const {
  protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ResMotor::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResMotor::kIdFieldNumber;
const int ResMotor::kCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResMotor::ResMotor()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_motor_2eproto::scc_info_ResMotor.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ResMotor)
}
ResMotor::ResMotor(const ResMotor& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&code_) -
    reinterpret_cast<char*>(&id_)) + sizeof(code_));
  // @@protoc_insertion_point(copy_constructor:dwarf.ResMotor)
}

void ResMotor::SharedCtor() {
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&code_) -
      reinterpret_cast<char*>(&id_)) + sizeof(code_));
}

ResMotor::~ResMotor() {
  // @@protoc_insertion_point(destructor:dwarf.ResMotor)
  SharedDtor();
}

void ResMotor::SharedDtor() {
}

void ResMotor::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ResMotor::descriptor() {
  ::protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResMotor& ResMotor::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_motor_2eproto::scc_info_ResMotor.base);
  return *internal_default_instance();
}


void ResMotor::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ResMotor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&code_) -
      reinterpret_cast<char*>(&id_)) + sizeof(code_));
  _internal_metadata_.Clear();
}

bool ResMotor::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ResMotor)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 code = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ResMotor)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ResMotor)
  return false;
#undef DO_
}

void ResMotor::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ResMotor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // int32 code = 2;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->code(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ResMotor)
}

::google::protobuf::uint8* ResMotor::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ResMotor)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // int32 code = 2;
  if (this->code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->code(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ResMotor)
  return target;
}

size_t ResMotor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ResMotor)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  // int32 code = 2;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResMotor::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ResMotor)
  GOOGLE_DCHECK_NE(&from, this);
  const ResMotor* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResMotor>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ResMotor)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ResMotor)
    MergeFrom(*source);
  }
}

void ResMotor::MergeFrom(const ResMotor& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ResMotor)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
}

void ResMotor::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ResMotor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResMotor::CopyFrom(const ResMotor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ResMotor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResMotor::IsInitialized() const {
  return true;
}

void ResMotor::Swap(ResMotor* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResMotor::InternalSwap(ResMotor* other) {
  using std::swap;
  swap(id_, other->id_);
  swap(code_, other->code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ResMotor::GetMetadata() const {
  protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqMotorStop::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqMotorStop::kIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqMotorStop::ReqMotorStop()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_motor_2eproto::scc_info_ReqMotorStop.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqMotorStop)
}
ReqMotorStop::ReqMotorStop(const ReqMotorStop& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqMotorStop)
}

void ReqMotorStop::SharedCtor() {
  id_ = 0;
}

ReqMotorStop::~ReqMotorStop() {
  // @@protoc_insertion_point(destructor:dwarf.ReqMotorStop)
  SharedDtor();
}

void ReqMotorStop::SharedDtor() {
}

void ReqMotorStop::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqMotorStop::descriptor() {
  ::protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqMotorStop& ReqMotorStop::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_motor_2eproto::scc_info_ReqMotorStop.base);
  return *internal_default_instance();
}


void ReqMotorStop::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqMotorStop)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_ = 0;
  _internal_metadata_.Clear();
}

bool ReqMotorStop::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqMotorStop)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqMotorStop)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqMotorStop)
  return false;
#undef DO_
}

void ReqMotorStop::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqMotorStop)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqMotorStop)
}

::google::protobuf::uint8* ReqMotorStop::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqMotorStop)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqMotorStop)
  return target;
}

size_t ReqMotorStop::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqMotorStop)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqMotorStop::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqMotorStop)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqMotorStop* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqMotorStop>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqMotorStop)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqMotorStop)
    MergeFrom(*source);
  }
}

void ReqMotorStop::MergeFrom(const ReqMotorStop& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqMotorStop)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id() != 0) {
    set_id(from.id());
  }
}

void ReqMotorStop::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqMotorStop)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqMotorStop::CopyFrom(const ReqMotorStop& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqMotorStop)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqMotorStop::IsInitialized() const {
  return true;
}

void ReqMotorStop::Swap(ReqMotorStop* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqMotorStop::InternalSwap(ReqMotorStop* other) {
  using std::swap;
  swap(id_, other->id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqMotorStop::GetMetadata() const {
  protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqMotorServiceJoystick::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqMotorServiceJoystick::kVectorAngleFieldNumber;
const int ReqMotorServiceJoystick::kVectorLengthFieldNumber;
const int ReqMotorServiceJoystick::kSpeedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqMotorServiceJoystick::ReqMotorServiceJoystick()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_motor_2eproto::scc_info_ReqMotorServiceJoystick.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqMotorServiceJoystick)
}
ReqMotorServiceJoystick::ReqMotorServiceJoystick(const ReqMotorServiceJoystick& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&vector_angle_, &from.vector_angle_,
    static_cast<size_t>(reinterpret_cast<char*>(&speed_) -
    reinterpret_cast<char*>(&vector_angle_)) + sizeof(speed_));
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqMotorServiceJoystick)
}

void ReqMotorServiceJoystick::SharedCtor() {
  ::memset(&vector_angle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&speed_) -
      reinterpret_cast<char*>(&vector_angle_)) + sizeof(speed_));
}

ReqMotorServiceJoystick::~ReqMotorServiceJoystick() {
  // @@protoc_insertion_point(destructor:dwarf.ReqMotorServiceJoystick)
  SharedDtor();
}

void ReqMotorServiceJoystick::SharedDtor() {
}

void ReqMotorServiceJoystick::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqMotorServiceJoystick::descriptor() {
  ::protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqMotorServiceJoystick& ReqMotorServiceJoystick::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_motor_2eproto::scc_info_ReqMotorServiceJoystick.base);
  return *internal_default_instance();
}


void ReqMotorServiceJoystick::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqMotorServiceJoystick)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&vector_angle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&speed_) -
      reinterpret_cast<char*>(&vector_angle_)) + sizeof(speed_));
  _internal_metadata_.Clear();
}

bool ReqMotorServiceJoystick::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqMotorServiceJoystick)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double vector_angle = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vector_angle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double vector_length = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vector_length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double speed = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &speed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqMotorServiceJoystick)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqMotorServiceJoystick)
  return false;
#undef DO_
}

void ReqMotorServiceJoystick::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqMotorServiceJoystick)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double vector_angle = 1;
  if (this->vector_angle() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->vector_angle(), output);
  }

  // double vector_length = 2;
  if (this->vector_length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->vector_length(), output);
  }

  // double speed = 3;
  if (this->speed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->speed(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqMotorServiceJoystick)
}

::google::protobuf::uint8* ReqMotorServiceJoystick::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqMotorServiceJoystick)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double vector_angle = 1;
  if (this->vector_angle() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->vector_angle(), target);
  }

  // double vector_length = 2;
  if (this->vector_length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->vector_length(), target);
  }

  // double speed = 3;
  if (this->speed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->speed(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqMotorServiceJoystick)
  return target;
}

size_t ReqMotorServiceJoystick::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqMotorServiceJoystick)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double vector_angle = 1;
  if (this->vector_angle() != 0) {
    total_size += 1 + 8;
  }

  // double vector_length = 2;
  if (this->vector_length() != 0) {
    total_size += 1 + 8;
  }

  // double speed = 3;
  if (this->speed() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqMotorServiceJoystick::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqMotorServiceJoystick)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqMotorServiceJoystick* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqMotorServiceJoystick>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqMotorServiceJoystick)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqMotorServiceJoystick)
    MergeFrom(*source);
  }
}

void ReqMotorServiceJoystick::MergeFrom(const ReqMotorServiceJoystick& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqMotorServiceJoystick)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.vector_angle() != 0) {
    set_vector_angle(from.vector_angle());
  }
  if (from.vector_length() != 0) {
    set_vector_length(from.vector_length());
  }
  if (from.speed() != 0) {
    set_speed(from.speed());
  }
}

void ReqMotorServiceJoystick::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqMotorServiceJoystick)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqMotorServiceJoystick::CopyFrom(const ReqMotorServiceJoystick& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqMotorServiceJoystick)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqMotorServiceJoystick::IsInitialized() const {
  return true;
}

void ReqMotorServiceJoystick::Swap(ReqMotorServiceJoystick* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqMotorServiceJoystick::InternalSwap(ReqMotorServiceJoystick* other) {
  using std::swap;
  swap(vector_angle_, other->vector_angle_);
  swap(vector_length_, other->vector_length_);
  swap(speed_, other->speed_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqMotorServiceJoystick::GetMetadata() const {
  protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqMotorServiceJoystickFixedAngle::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqMotorServiceJoystickFixedAngle::kVectorAngleFieldNumber;
const int ReqMotorServiceJoystickFixedAngle::kVectorLengthFieldNumber;
const int ReqMotorServiceJoystickFixedAngle::kSpeedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqMotorServiceJoystickFixedAngle::ReqMotorServiceJoystickFixedAngle()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_motor_2eproto::scc_info_ReqMotorServiceJoystickFixedAngle.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqMotorServiceJoystickFixedAngle)
}
ReqMotorServiceJoystickFixedAngle::ReqMotorServiceJoystickFixedAngle(const ReqMotorServiceJoystickFixedAngle& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&vector_angle_, &from.vector_angle_,
    static_cast<size_t>(reinterpret_cast<char*>(&speed_) -
    reinterpret_cast<char*>(&vector_angle_)) + sizeof(speed_));
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqMotorServiceJoystickFixedAngle)
}

void ReqMotorServiceJoystickFixedAngle::SharedCtor() {
  ::memset(&vector_angle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&speed_) -
      reinterpret_cast<char*>(&vector_angle_)) + sizeof(speed_));
}

ReqMotorServiceJoystickFixedAngle::~ReqMotorServiceJoystickFixedAngle() {
  // @@protoc_insertion_point(destructor:dwarf.ReqMotorServiceJoystickFixedAngle)
  SharedDtor();
}

void ReqMotorServiceJoystickFixedAngle::SharedDtor() {
}

void ReqMotorServiceJoystickFixedAngle::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqMotorServiceJoystickFixedAngle::descriptor() {
  ::protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqMotorServiceJoystickFixedAngle& ReqMotorServiceJoystickFixedAngle::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_motor_2eproto::scc_info_ReqMotorServiceJoystickFixedAngle.base);
  return *internal_default_instance();
}


void ReqMotorServiceJoystickFixedAngle::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqMotorServiceJoystickFixedAngle)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&vector_angle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&speed_) -
      reinterpret_cast<char*>(&vector_angle_)) + sizeof(speed_));
  _internal_metadata_.Clear();
}

bool ReqMotorServiceJoystickFixedAngle::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqMotorServiceJoystickFixedAngle)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double vector_angle = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vector_angle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double vector_length = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vector_length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double speed = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &speed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqMotorServiceJoystickFixedAngle)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqMotorServiceJoystickFixedAngle)
  return false;
#undef DO_
}

void ReqMotorServiceJoystickFixedAngle::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqMotorServiceJoystickFixedAngle)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double vector_angle = 1;
  if (this->vector_angle() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->vector_angle(), output);
  }

  // double vector_length = 2;
  if (this->vector_length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->vector_length(), output);
  }

  // double speed = 3;
  if (this->speed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->speed(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqMotorServiceJoystickFixedAngle)
}

::google::protobuf::uint8* ReqMotorServiceJoystickFixedAngle::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqMotorServiceJoystickFixedAngle)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double vector_angle = 1;
  if (this->vector_angle() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->vector_angle(), target);
  }

  // double vector_length = 2;
  if (this->vector_length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->vector_length(), target);
  }

  // double speed = 3;
  if (this->speed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->speed(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqMotorServiceJoystickFixedAngle)
  return target;
}

size_t ReqMotorServiceJoystickFixedAngle::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqMotorServiceJoystickFixedAngle)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double vector_angle = 1;
  if (this->vector_angle() != 0) {
    total_size += 1 + 8;
  }

  // double vector_length = 2;
  if (this->vector_length() != 0) {
    total_size += 1 + 8;
  }

  // double speed = 3;
  if (this->speed() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqMotorServiceJoystickFixedAngle::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqMotorServiceJoystickFixedAngle)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqMotorServiceJoystickFixedAngle* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqMotorServiceJoystickFixedAngle>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqMotorServiceJoystickFixedAngle)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqMotorServiceJoystickFixedAngle)
    MergeFrom(*source);
  }
}

void ReqMotorServiceJoystickFixedAngle::MergeFrom(const ReqMotorServiceJoystickFixedAngle& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqMotorServiceJoystickFixedAngle)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.vector_angle() != 0) {
    set_vector_angle(from.vector_angle());
  }
  if (from.vector_length() != 0) {
    set_vector_length(from.vector_length());
  }
  if (from.speed() != 0) {
    set_speed(from.speed());
  }
}

void ReqMotorServiceJoystickFixedAngle::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqMotorServiceJoystickFixedAngle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqMotorServiceJoystickFixedAngle::CopyFrom(const ReqMotorServiceJoystickFixedAngle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqMotorServiceJoystickFixedAngle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqMotorServiceJoystickFixedAngle::IsInitialized() const {
  return true;
}

void ReqMotorServiceJoystickFixedAngle::Swap(ReqMotorServiceJoystickFixedAngle* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqMotorServiceJoystickFixedAngle::InternalSwap(ReqMotorServiceJoystickFixedAngle* other) {
  using std::swap;
  swap(vector_angle_, other->vector_angle_);
  swap(vector_length_, other->vector_length_);
  swap(speed_, other->speed_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqMotorServiceJoystickFixedAngle::GetMetadata() const {
  protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqMotorServiceJoystickStop::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqMotorServiceJoystickStop::ReqMotorServiceJoystickStop()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_motor_2eproto::scc_info_ReqMotorServiceJoystickStop.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqMotorServiceJoystickStop)
}
ReqMotorServiceJoystickStop::ReqMotorServiceJoystickStop(const ReqMotorServiceJoystickStop& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqMotorServiceJoystickStop)
}

void ReqMotorServiceJoystickStop::SharedCtor() {
}

ReqMotorServiceJoystickStop::~ReqMotorServiceJoystickStop() {
  // @@protoc_insertion_point(destructor:dwarf.ReqMotorServiceJoystickStop)
  SharedDtor();
}

void ReqMotorServiceJoystickStop::SharedDtor() {
}

void ReqMotorServiceJoystickStop::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqMotorServiceJoystickStop::descriptor() {
  ::protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqMotorServiceJoystickStop& ReqMotorServiceJoystickStop::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_motor_2eproto::scc_info_ReqMotorServiceJoystickStop.base);
  return *internal_default_instance();
}


void ReqMotorServiceJoystickStop::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqMotorServiceJoystickStop)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool ReqMotorServiceJoystickStop::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqMotorServiceJoystickStop)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqMotorServiceJoystickStop)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqMotorServiceJoystickStop)
  return false;
#undef DO_
}

void ReqMotorServiceJoystickStop::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqMotorServiceJoystickStop)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqMotorServiceJoystickStop)
}

::google::protobuf::uint8* ReqMotorServiceJoystickStop::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqMotorServiceJoystickStop)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqMotorServiceJoystickStop)
  return target;
}

size_t ReqMotorServiceJoystickStop::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqMotorServiceJoystickStop)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqMotorServiceJoystickStop::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqMotorServiceJoystickStop)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqMotorServiceJoystickStop* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqMotorServiceJoystickStop>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqMotorServiceJoystickStop)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqMotorServiceJoystickStop)
    MergeFrom(*source);
  }
}

void ReqMotorServiceJoystickStop::MergeFrom(const ReqMotorServiceJoystickStop& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqMotorServiceJoystickStop)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ReqMotorServiceJoystickStop::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqMotorServiceJoystickStop)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqMotorServiceJoystickStop::CopyFrom(const ReqMotorServiceJoystickStop& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqMotorServiceJoystickStop)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqMotorServiceJoystickStop::IsInitialized() const {
  return true;
}

void ReqMotorServiceJoystickStop::Swap(ReqMotorServiceJoystickStop* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqMotorServiceJoystickStop::InternalSwap(ReqMotorServiceJoystickStop* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqMotorServiceJoystickStop::GetMetadata() const {
  protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqDualCameraLinkage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqDualCameraLinkage::kXFieldNumber;
const int ReqDualCameraLinkage::kYFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqDualCameraLinkage::ReqDualCameraLinkage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_motor_2eproto::scc_info_ReqDualCameraLinkage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqDualCameraLinkage)
}
ReqDualCameraLinkage::ReqDualCameraLinkage(const ReqDualCameraLinkage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&y_) -
    reinterpret_cast<char*>(&x_)) + sizeof(y_));
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqDualCameraLinkage)
}

void ReqDualCameraLinkage::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&x_)) + sizeof(y_));
}

ReqDualCameraLinkage::~ReqDualCameraLinkage() {
  // @@protoc_insertion_point(destructor:dwarf.ReqDualCameraLinkage)
  SharedDtor();
}

void ReqDualCameraLinkage::SharedDtor() {
}

void ReqDualCameraLinkage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqDualCameraLinkage::descriptor() {
  ::protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqDualCameraLinkage& ReqDualCameraLinkage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_motor_2eproto::scc_info_ReqDualCameraLinkage.base);
  return *internal_default_instance();
}


void ReqDualCameraLinkage::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqDualCameraLinkage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&x_)) + sizeof(y_));
  _internal_metadata_.Clear();
}

bool ReqDualCameraLinkage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqDualCameraLinkage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqDualCameraLinkage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqDualCameraLinkage)
  return false;
#undef DO_
}

void ReqDualCameraLinkage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqDualCameraLinkage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->x(), output);
  }

  // int32 y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->y(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqDualCameraLinkage)
}

::google::protobuf::uint8* ReqDualCameraLinkage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqDualCameraLinkage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->x(), target);
  }

  // int32 y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->y(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqDualCameraLinkage)
  return target;
}

size_t ReqDualCameraLinkage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqDualCameraLinkage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 x = 1;
  if (this->x() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->x());
  }

  // int32 y = 2;
  if (this->y() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->y());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqDualCameraLinkage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqDualCameraLinkage)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqDualCameraLinkage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqDualCameraLinkage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqDualCameraLinkage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqDualCameraLinkage)
    MergeFrom(*source);
  }
}

void ReqDualCameraLinkage::MergeFrom(const ReqDualCameraLinkage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqDualCameraLinkage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
}

void ReqDualCameraLinkage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqDualCameraLinkage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqDualCameraLinkage::CopyFrom(const ReqDualCameraLinkage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqDualCameraLinkage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqDualCameraLinkage::IsInitialized() const {
  return true;
}

void ReqDualCameraLinkage::Swap(ReqDualCameraLinkage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqDualCameraLinkage::InternalSwap(ReqDualCameraLinkage* other) {
  using std::swap;
  swap(x_, other->x_);
  swap(y_, other->y_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqDualCameraLinkage::GetMetadata() const {
  protobuf_motor_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_motor_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace dwarf
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqMotorRun* Arena::CreateMaybeMessage< ::dwarf::ReqMotorRun >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqMotorRun >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ResMotor* Arena::CreateMaybeMessage< ::dwarf::ResMotor >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ResMotor >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqMotorStop* Arena::CreateMaybeMessage< ::dwarf::ReqMotorStop >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqMotorStop >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqMotorServiceJoystick* Arena::CreateMaybeMessage< ::dwarf::ReqMotorServiceJoystick >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqMotorServiceJoystick >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqMotorServiceJoystickFixedAngle* Arena::CreateMaybeMessage< ::dwarf::ReqMotorServiceJoystickFixedAngle >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqMotorServiceJoystickFixedAngle >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqMotorServiceJoystickStop* Arena::CreateMaybeMessage< ::dwarf::ReqMotorServiceJoystickStop >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqMotorServiceJoystickStop >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqDualCameraLinkage* Arena::CreateMaybeMessage< ::dwarf::ReqDualCameraLinkage >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqDualCameraLinkage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
