// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify.proto

#ifndef PROTOBUF_INCLUDED_notify_2eproto
#define PROTOBUF_INCLUDED_notify_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_notify_2eproto 

namespace protobuf_notify_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[16];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_notify_2eproto
namespace dwarf {
class ResNotifyBattery;
class ResNotifyBatteryDefaultTypeInternal;
extern ResNotifyBatteryDefaultTypeInternal _ResNotifyBattery_default_instance_;
class ResNotifyChargeStatus;
class ResNotifyChargeStatusDefaultTypeInternal;
extern ResNotifyChargeStatusDefaultTypeInternal _ResNotifyChargeStatus_default_instance_;
class ResNotifyDarkOperationState;
class ResNotifyDarkOperationStateDefaultTypeInternal;
extern ResNotifyDarkOperationStateDefaultTypeInternal _ResNotifyDarkOperationState_default_instance_;
class ResNotifyEqSolvingState;
class ResNotifyEqSolvingStateDefaultTypeInternal;
extern ResNotifyEqSolvingStateDefaultTypeInternal _ResNotifyEqSolvingState_default_instance_;
class ResNotifyFocus;
class ResNotifyFocusDefaultTypeInternal;
extern ResNotifyFocusDefaultTypeInternal _ResNotifyFocus_default_instance_;
class ResNotifyOneClickGotoState;
class ResNotifyOneClickGotoStateDefaultTypeInternal;
extern ResNotifyOneClickGotoStateDefaultTypeInternal _ResNotifyOneClickGotoState_default_instance_;
class ResNotifyOperationState;
class ResNotifyOperationStateDefaultTypeInternal;
extern ResNotifyOperationStateDefaultTypeInternal _ResNotifyOperationState_default_instance_;
class ResNotifyProgressCaptureRawDark;
class ResNotifyProgressCaptureRawDarkDefaultTypeInternal;
extern ResNotifyProgressCaptureRawDarkDefaultTypeInternal _ResNotifyProgressCaptureRawDark_default_instance_;
class ResNotifyProgressCaptureRawLiveStacking;
class ResNotifyProgressCaptureRawLiveStackingDefaultTypeInternal;
extern ResNotifyProgressCaptureRawLiveStackingDefaultTypeInternal _ResNotifyProgressCaptureRawLiveStacking_default_instance_;
class ResNotifyProgressCaptureWideRawLiveStacking;
class ResNotifyProgressCaptureWideRawLiveStackingDefaultTypeInternal;
extern ResNotifyProgressCaptureWideRawLiveStackingDefaultTypeInternal _ResNotifyProgressCaptureWideRawLiveStacking_default_instance_;
class ResNotifySDcardInfo;
class ResNotifySDcardInfoDefaultTypeInternal;
extern ResNotifySDcardInfoDefaultTypeInternal _ResNotifySDcardInfo_default_instance_;
class ResNotifyStateAstroCalibration;
class ResNotifyStateAstroCalibrationDefaultTypeInternal;
extern ResNotifyStateAstroCalibrationDefaultTypeInternal _ResNotifyStateAstroCalibration_default_instance_;
class ResNotifyStateAstroGoto;
class ResNotifyStateAstroGotoDefaultTypeInternal;
extern ResNotifyStateAstroGotoDefaultTypeInternal _ResNotifyStateAstroGoto_default_instance_;
class ResNotifyStateAstroTracking;
class ResNotifyStateAstroTrackingDefaultTypeInternal;
extern ResNotifyStateAstroTrackingDefaultTypeInternal _ResNotifyStateAstroTracking_default_instance_;
class ResNotifyTemperature;
class ResNotifyTemperatureDefaultTypeInternal;
extern ResNotifyTemperatureDefaultTypeInternal _ResNotifyTemperature_default_instance_;
class ResNotifyWideOperationState;
class ResNotifyWideOperationStateDefaultTypeInternal;
extern ResNotifyWideOperationStateDefaultTypeInternal _ResNotifyWideOperationState_default_instance_;
}  // namespace dwarf
namespace google {
namespace protobuf {
template<> ::dwarf::ResNotifyBattery* Arena::CreateMaybeMessage<::dwarf::ResNotifyBattery>(Arena*);
template<> ::dwarf::ResNotifyChargeStatus* Arena::CreateMaybeMessage<::dwarf::ResNotifyChargeStatus>(Arena*);
template<> ::dwarf::ResNotifyDarkOperationState* Arena::CreateMaybeMessage<::dwarf::ResNotifyDarkOperationState>(Arena*);
template<> ::dwarf::ResNotifyEqSolvingState* Arena::CreateMaybeMessage<::dwarf::ResNotifyEqSolvingState>(Arena*);
template<> ::dwarf::ResNotifyFocus* Arena::CreateMaybeMessage<::dwarf::ResNotifyFocus>(Arena*);
template<> ::dwarf::ResNotifyOneClickGotoState* Arena::CreateMaybeMessage<::dwarf::ResNotifyOneClickGotoState>(Arena*);
template<> ::dwarf::ResNotifyOperationState* Arena::CreateMaybeMessage<::dwarf::ResNotifyOperationState>(Arena*);
template<> ::dwarf::ResNotifyProgressCaptureRawDark* Arena::CreateMaybeMessage<::dwarf::ResNotifyProgressCaptureRawDark>(Arena*);
template<> ::dwarf::ResNotifyProgressCaptureRawLiveStacking* Arena::CreateMaybeMessage<::dwarf::ResNotifyProgressCaptureRawLiveStacking>(Arena*);
template<> ::dwarf::ResNotifyProgressCaptureWideRawLiveStacking* Arena::CreateMaybeMessage<::dwarf::ResNotifyProgressCaptureWideRawLiveStacking>(Arena*);
template<> ::dwarf::ResNotifySDcardInfo* Arena::CreateMaybeMessage<::dwarf::ResNotifySDcardInfo>(Arena*);
template<> ::dwarf::ResNotifyStateAstroCalibration* Arena::CreateMaybeMessage<::dwarf::ResNotifyStateAstroCalibration>(Arena*);
template<> ::dwarf::ResNotifyStateAstroGoto* Arena::CreateMaybeMessage<::dwarf::ResNotifyStateAstroGoto>(Arena*);
template<> ::dwarf::ResNotifyStateAstroTracking* Arena::CreateMaybeMessage<::dwarf::ResNotifyStateAstroTracking>(Arena*);
template<> ::dwarf::ResNotifyTemperature* Arena::CreateMaybeMessage<::dwarf::ResNotifyTemperature>(Arena*);
template<> ::dwarf::ResNotifyWideOperationState* Arena::CreateMaybeMessage<::dwarf::ResNotifyWideOperationState>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace dwarf {

// ===================================================================

class ResNotifyBattery : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyBattery) */ {
 public:
  ResNotifyBattery();
  virtual ~ResNotifyBattery();

  ResNotifyBattery(const ResNotifyBattery& from);

  inline ResNotifyBattery& operator=(const ResNotifyBattery& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyBattery(ResNotifyBattery&& from) noexcept
    : ResNotifyBattery() {
    *this = ::std::move(from);
  }

  inline ResNotifyBattery& operator=(ResNotifyBattery&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyBattery& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyBattery* internal_default_instance() {
    return reinterpret_cast<const ResNotifyBattery*>(
               &_ResNotifyBattery_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ResNotifyBattery* other);
  friend void swap(ResNotifyBattery& a, ResNotifyBattery& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyBattery* New() const final {
    return CreateMaybeMessage<ResNotifyBattery>(NULL);
  }

  ResNotifyBattery* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyBattery>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyBattery& from);
  void MergeFrom(const ResNotifyBattery& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyBattery* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyBattery)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyChargeStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyChargeStatus) */ {
 public:
  ResNotifyChargeStatus();
  virtual ~ResNotifyChargeStatus();

  ResNotifyChargeStatus(const ResNotifyChargeStatus& from);

  inline ResNotifyChargeStatus& operator=(const ResNotifyChargeStatus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyChargeStatus(ResNotifyChargeStatus&& from) noexcept
    : ResNotifyChargeStatus() {
    *this = ::std::move(from);
  }

  inline ResNotifyChargeStatus& operator=(ResNotifyChargeStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyChargeStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyChargeStatus* internal_default_instance() {
    return reinterpret_cast<const ResNotifyChargeStatus*>(
               &_ResNotifyChargeStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ResNotifyChargeStatus* other);
  friend void swap(ResNotifyChargeStatus& a, ResNotifyChargeStatus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyChargeStatus* New() const final {
    return CreateMaybeMessage<ResNotifyChargeStatus>(NULL);
  }

  ResNotifyChargeStatus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyChargeStatus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyChargeStatus& from);
  void MergeFrom(const ResNotifyChargeStatus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyChargeStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyChargeStatus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifySDcardInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifySDcardInfo) */ {
 public:
  ResNotifySDcardInfo();
  virtual ~ResNotifySDcardInfo();

  ResNotifySDcardInfo(const ResNotifySDcardInfo& from);

  inline ResNotifySDcardInfo& operator=(const ResNotifySDcardInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifySDcardInfo(ResNotifySDcardInfo&& from) noexcept
    : ResNotifySDcardInfo() {
    *this = ::std::move(from);
  }

  inline ResNotifySDcardInfo& operator=(ResNotifySDcardInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifySDcardInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifySDcardInfo* internal_default_instance() {
    return reinterpret_cast<const ResNotifySDcardInfo*>(
               &_ResNotifySDcardInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ResNotifySDcardInfo* other);
  friend void swap(ResNotifySDcardInfo& a, ResNotifySDcardInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifySDcardInfo* New() const final {
    return CreateMaybeMessage<ResNotifySDcardInfo>(NULL);
  }

  ResNotifySDcardInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifySDcardInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifySDcardInfo& from);
  void MergeFrom(const ResNotifySDcardInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifySDcardInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 total = 1;
  void clear_total();
  static const int kTotalFieldNumber = 1;
  ::google::protobuf::int64 total() const;
  void set_total(::google::protobuf::int64 value);

  // int64 available = 2;
  void clear_available();
  static const int kAvailableFieldNumber = 2;
  ::google::protobuf::int64 available() const;
  void set_available(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifySDcardInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 total_;
  ::google::protobuf::int64 available_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyDarkOperationState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyDarkOperationState) */ {
 public:
  ResNotifyDarkOperationState();
  virtual ~ResNotifyDarkOperationState();

  ResNotifyDarkOperationState(const ResNotifyDarkOperationState& from);

  inline ResNotifyDarkOperationState& operator=(const ResNotifyDarkOperationState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyDarkOperationState(ResNotifyDarkOperationState&& from) noexcept
    : ResNotifyDarkOperationState() {
    *this = ::std::move(from);
  }

  inline ResNotifyDarkOperationState& operator=(ResNotifyDarkOperationState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyDarkOperationState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyDarkOperationState* internal_default_instance() {
    return reinterpret_cast<const ResNotifyDarkOperationState*>(
               &_ResNotifyDarkOperationState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ResNotifyDarkOperationState* other);
  friend void swap(ResNotifyDarkOperationState& a, ResNotifyDarkOperationState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyDarkOperationState* New() const final {
    return CreateMaybeMessage<ResNotifyDarkOperationState>(NULL);
  }

  ResNotifyDarkOperationState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyDarkOperationState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyDarkOperationState& from);
  void MergeFrom(const ResNotifyDarkOperationState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyDarkOperationState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyDarkOperationState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyProgressCaptureRawDark : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyProgressCaptureRawDark) */ {
 public:
  ResNotifyProgressCaptureRawDark();
  virtual ~ResNotifyProgressCaptureRawDark();

  ResNotifyProgressCaptureRawDark(const ResNotifyProgressCaptureRawDark& from);

  inline ResNotifyProgressCaptureRawDark& operator=(const ResNotifyProgressCaptureRawDark& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyProgressCaptureRawDark(ResNotifyProgressCaptureRawDark&& from) noexcept
    : ResNotifyProgressCaptureRawDark() {
    *this = ::std::move(from);
  }

  inline ResNotifyProgressCaptureRawDark& operator=(ResNotifyProgressCaptureRawDark&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyProgressCaptureRawDark& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyProgressCaptureRawDark* internal_default_instance() {
    return reinterpret_cast<const ResNotifyProgressCaptureRawDark*>(
               &_ResNotifyProgressCaptureRawDark_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ResNotifyProgressCaptureRawDark* other);
  friend void swap(ResNotifyProgressCaptureRawDark& a, ResNotifyProgressCaptureRawDark& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyProgressCaptureRawDark* New() const final {
    return CreateMaybeMessage<ResNotifyProgressCaptureRawDark>(NULL);
  }

  ResNotifyProgressCaptureRawDark* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyProgressCaptureRawDark>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyProgressCaptureRawDark& from);
  void MergeFrom(const ResNotifyProgressCaptureRawDark& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyProgressCaptureRawDark* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 current_count = 1;
  void clear_current_count();
  static const int kCurrentCountFieldNumber = 1;
  ::google::protobuf::int32 current_count() const;
  void set_current_count(::google::protobuf::int32 value);

  // int32 total_count = 2;
  void clear_total_count();
  static const int kTotalCountFieldNumber = 2;
  ::google::protobuf::int32 total_count() const;
  void set_total_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyProgressCaptureRawDark)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 current_count_;
  ::google::protobuf::int32 total_count_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyOperationState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyOperationState) */ {
 public:
  ResNotifyOperationState();
  virtual ~ResNotifyOperationState();

  ResNotifyOperationState(const ResNotifyOperationState& from);

  inline ResNotifyOperationState& operator=(const ResNotifyOperationState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyOperationState(ResNotifyOperationState&& from) noexcept
    : ResNotifyOperationState() {
    *this = ::std::move(from);
  }

  inline ResNotifyOperationState& operator=(ResNotifyOperationState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyOperationState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyOperationState* internal_default_instance() {
    return reinterpret_cast<const ResNotifyOperationState*>(
               &_ResNotifyOperationState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ResNotifyOperationState* other);
  friend void swap(ResNotifyOperationState& a, ResNotifyOperationState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyOperationState* New() const final {
    return CreateMaybeMessage<ResNotifyOperationState>(NULL);
  }

  ResNotifyOperationState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyOperationState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyOperationState& from);
  void MergeFrom(const ResNotifyOperationState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyOperationState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyOperationState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyProgressCaptureRawLiveStacking : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyProgressCaptureRawLiveStacking) */ {
 public:
  ResNotifyProgressCaptureRawLiveStacking();
  virtual ~ResNotifyProgressCaptureRawLiveStacking();

  ResNotifyProgressCaptureRawLiveStacking(const ResNotifyProgressCaptureRawLiveStacking& from);

  inline ResNotifyProgressCaptureRawLiveStacking& operator=(const ResNotifyProgressCaptureRawLiveStacking& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyProgressCaptureRawLiveStacking(ResNotifyProgressCaptureRawLiveStacking&& from) noexcept
    : ResNotifyProgressCaptureRawLiveStacking() {
    *this = ::std::move(from);
  }

  inline ResNotifyProgressCaptureRawLiveStacking& operator=(ResNotifyProgressCaptureRawLiveStacking&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyProgressCaptureRawLiveStacking& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyProgressCaptureRawLiveStacking* internal_default_instance() {
    return reinterpret_cast<const ResNotifyProgressCaptureRawLiveStacking*>(
               &_ResNotifyProgressCaptureRawLiveStacking_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(ResNotifyProgressCaptureRawLiveStacking* other);
  friend void swap(ResNotifyProgressCaptureRawLiveStacking& a, ResNotifyProgressCaptureRawLiveStacking& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyProgressCaptureRawLiveStacking* New() const final {
    return CreateMaybeMessage<ResNotifyProgressCaptureRawLiveStacking>(NULL);
  }

  ResNotifyProgressCaptureRawLiveStacking* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyProgressCaptureRawLiveStacking>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyProgressCaptureRawLiveStacking& from);
  void MergeFrom(const ResNotifyProgressCaptureRawLiveStacking& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyProgressCaptureRawLiveStacking* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 current_count = 1;
  void clear_current_count();
  static const int kCurrentCountFieldNumber = 1;
  ::google::protobuf::int32 current_count() const;
  void set_current_count(::google::protobuf::int32 value);

  // int32 total_count = 2;
  void clear_total_count();
  static const int kTotalCountFieldNumber = 2;
  ::google::protobuf::int32 total_count() const;
  void set_total_count(::google::protobuf::int32 value);

  // int32 stacked_count = 3;
  void clear_stacked_count();
  static const int kStackedCountFieldNumber = 3;
  ::google::protobuf::int32 stacked_count() const;
  void set_stacked_count(::google::protobuf::int32 value);

  // int32 rejected_count = 4;
  void clear_rejected_count();
  static const int kRejectedCountFieldNumber = 4;
  ::google::protobuf::int32 rejected_count() const;
  void set_rejected_count(::google::protobuf::int32 value);

  // int32 exp_index = 5;
  void clear_exp_index();
  static const int kExpIndexFieldNumber = 5;
  ::google::protobuf::int32 exp_index() const;
  void set_exp_index(::google::protobuf::int32 value);

  // int32 gain_index = 6;
  void clear_gain_index();
  static const int kGainIndexFieldNumber = 6;
  ::google::protobuf::int32 gain_index() const;
  void set_gain_index(::google::protobuf::int32 value);

  // int32 bin_index = 7;
  void clear_bin_index();
  static const int kBinIndexFieldNumber = 7;
  ::google::protobuf::int32 bin_index() const;
  void set_bin_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyProgressCaptureRawLiveStacking)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 current_count_;
  ::google::protobuf::int32 total_count_;
  ::google::protobuf::int32 stacked_count_;
  ::google::protobuf::int32 rejected_count_;
  ::google::protobuf::int32 exp_index_;
  ::google::protobuf::int32 gain_index_;
  ::google::protobuf::int32 bin_index_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyStateAstroCalibration : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyStateAstroCalibration) */ {
 public:
  ResNotifyStateAstroCalibration();
  virtual ~ResNotifyStateAstroCalibration();

  ResNotifyStateAstroCalibration(const ResNotifyStateAstroCalibration& from);

  inline ResNotifyStateAstroCalibration& operator=(const ResNotifyStateAstroCalibration& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyStateAstroCalibration(ResNotifyStateAstroCalibration&& from) noexcept
    : ResNotifyStateAstroCalibration() {
    *this = ::std::move(from);
  }

  inline ResNotifyStateAstroCalibration& operator=(ResNotifyStateAstroCalibration&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyStateAstroCalibration& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyStateAstroCalibration* internal_default_instance() {
    return reinterpret_cast<const ResNotifyStateAstroCalibration*>(
               &_ResNotifyStateAstroCalibration_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(ResNotifyStateAstroCalibration* other);
  friend void swap(ResNotifyStateAstroCalibration& a, ResNotifyStateAstroCalibration& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyStateAstroCalibration* New() const final {
    return CreateMaybeMessage<ResNotifyStateAstroCalibration>(NULL);
  }

  ResNotifyStateAstroCalibration* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyStateAstroCalibration>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyStateAstroCalibration& from);
  void MergeFrom(const ResNotifyStateAstroCalibration& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyStateAstroCalibration* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // int32 code = 2;
  void clear_code();
  static const int kCodeFieldNumber = 2;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyStateAstroCalibration)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyStateAstroGoto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyStateAstroGoto) */ {
 public:
  ResNotifyStateAstroGoto();
  virtual ~ResNotifyStateAstroGoto();

  ResNotifyStateAstroGoto(const ResNotifyStateAstroGoto& from);

  inline ResNotifyStateAstroGoto& operator=(const ResNotifyStateAstroGoto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyStateAstroGoto(ResNotifyStateAstroGoto&& from) noexcept
    : ResNotifyStateAstroGoto() {
    *this = ::std::move(from);
  }

  inline ResNotifyStateAstroGoto& operator=(ResNotifyStateAstroGoto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyStateAstroGoto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyStateAstroGoto* internal_default_instance() {
    return reinterpret_cast<const ResNotifyStateAstroGoto*>(
               &_ResNotifyStateAstroGoto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(ResNotifyStateAstroGoto* other);
  friend void swap(ResNotifyStateAstroGoto& a, ResNotifyStateAstroGoto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyStateAstroGoto* New() const final {
    return CreateMaybeMessage<ResNotifyStateAstroGoto>(NULL);
  }

  ResNotifyStateAstroGoto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyStateAstroGoto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyStateAstroGoto& from);
  void MergeFrom(const ResNotifyStateAstroGoto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyStateAstroGoto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // int32 code = 2;
  void clear_code();
  static const int kCodeFieldNumber = 2;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyStateAstroGoto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyStateAstroTracking : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyStateAstroTracking) */ {
 public:
  ResNotifyStateAstroTracking();
  virtual ~ResNotifyStateAstroTracking();

  ResNotifyStateAstroTracking(const ResNotifyStateAstroTracking& from);

  inline ResNotifyStateAstroTracking& operator=(const ResNotifyStateAstroTracking& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyStateAstroTracking(ResNotifyStateAstroTracking&& from) noexcept
    : ResNotifyStateAstroTracking() {
    *this = ::std::move(from);
  }

  inline ResNotifyStateAstroTracking& operator=(ResNotifyStateAstroTracking&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyStateAstroTracking& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyStateAstroTracking* internal_default_instance() {
    return reinterpret_cast<const ResNotifyStateAstroTracking*>(
               &_ResNotifyStateAstroTracking_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(ResNotifyStateAstroTracking* other);
  friend void swap(ResNotifyStateAstroTracking& a, ResNotifyStateAstroTracking& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyStateAstroTracking* New() const final {
    return CreateMaybeMessage<ResNotifyStateAstroTracking>(NULL);
  }

  ResNotifyStateAstroTracking* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyStateAstroTracking>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyStateAstroTracking& from);
  void MergeFrom(const ResNotifyStateAstroTracking& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyStateAstroTracking* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyStateAstroTracking)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyOneClickGotoState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyOneClickGotoState) */ {
 public:
  ResNotifyOneClickGotoState();
  virtual ~ResNotifyOneClickGotoState();

  ResNotifyOneClickGotoState(const ResNotifyOneClickGotoState& from);

  inline ResNotifyOneClickGotoState& operator=(const ResNotifyOneClickGotoState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyOneClickGotoState(ResNotifyOneClickGotoState&& from) noexcept
    : ResNotifyOneClickGotoState() {
    *this = ::std::move(from);
  }

  inline ResNotifyOneClickGotoState& operator=(ResNotifyOneClickGotoState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyOneClickGotoState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyOneClickGotoState* internal_default_instance() {
    return reinterpret_cast<const ResNotifyOneClickGotoState*>(
               &_ResNotifyOneClickGotoState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  void Swap(ResNotifyOneClickGotoState* other);
  friend void swap(ResNotifyOneClickGotoState& a, ResNotifyOneClickGotoState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyOneClickGotoState* New() const final {
    return CreateMaybeMessage<ResNotifyOneClickGotoState>(NULL);
  }

  ResNotifyOneClickGotoState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyOneClickGotoState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyOneClickGotoState& from);
  void MergeFrom(const ResNotifyOneClickGotoState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyOneClickGotoState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 step = 1;
  void clear_step();
  static const int kStepFieldNumber = 1;
  ::google::protobuf::int32 step() const;
  void set_step(::google::protobuf::int32 value);

  // int32 state = 2;
  void clear_state();
  static const int kStateFieldNumber = 2;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // int32 code = 3;
  void clear_code();
  static const int kCodeFieldNumber = 3;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyOneClickGotoState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 step_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyWideOperationState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyWideOperationState) */ {
 public:
  ResNotifyWideOperationState();
  virtual ~ResNotifyWideOperationState();

  ResNotifyWideOperationState(const ResNotifyWideOperationState& from);

  inline ResNotifyWideOperationState& operator=(const ResNotifyWideOperationState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyWideOperationState(ResNotifyWideOperationState&& from) noexcept
    : ResNotifyWideOperationState() {
    *this = ::std::move(from);
  }

  inline ResNotifyWideOperationState& operator=(ResNotifyWideOperationState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyWideOperationState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyWideOperationState* internal_default_instance() {
    return reinterpret_cast<const ResNotifyWideOperationState*>(
               &_ResNotifyWideOperationState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  void Swap(ResNotifyWideOperationState* other);
  friend void swap(ResNotifyWideOperationState& a, ResNotifyWideOperationState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyWideOperationState* New() const final {
    return CreateMaybeMessage<ResNotifyWideOperationState>(NULL);
  }

  ResNotifyWideOperationState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyWideOperationState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyWideOperationState& from);
  void MergeFrom(const ResNotifyWideOperationState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyWideOperationState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyWideOperationState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyProgressCaptureWideRawLiveStacking : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyProgressCaptureWideRawLiveStacking) */ {
 public:
  ResNotifyProgressCaptureWideRawLiveStacking();
  virtual ~ResNotifyProgressCaptureWideRawLiveStacking();

  ResNotifyProgressCaptureWideRawLiveStacking(const ResNotifyProgressCaptureWideRawLiveStacking& from);

  inline ResNotifyProgressCaptureWideRawLiveStacking& operator=(const ResNotifyProgressCaptureWideRawLiveStacking& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyProgressCaptureWideRawLiveStacking(ResNotifyProgressCaptureWideRawLiveStacking&& from) noexcept
    : ResNotifyProgressCaptureWideRawLiveStacking() {
    *this = ::std::move(from);
  }

  inline ResNotifyProgressCaptureWideRawLiveStacking& operator=(ResNotifyProgressCaptureWideRawLiveStacking&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyProgressCaptureWideRawLiveStacking& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyProgressCaptureWideRawLiveStacking* internal_default_instance() {
    return reinterpret_cast<const ResNotifyProgressCaptureWideRawLiveStacking*>(
               &_ResNotifyProgressCaptureWideRawLiveStacking_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    12;

  void Swap(ResNotifyProgressCaptureWideRawLiveStacking* other);
  friend void swap(ResNotifyProgressCaptureWideRawLiveStacking& a, ResNotifyProgressCaptureWideRawLiveStacking& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyProgressCaptureWideRawLiveStacking* New() const final {
    return CreateMaybeMessage<ResNotifyProgressCaptureWideRawLiveStacking>(NULL);
  }

  ResNotifyProgressCaptureWideRawLiveStacking* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyProgressCaptureWideRawLiveStacking>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyProgressCaptureWideRawLiveStacking& from);
  void MergeFrom(const ResNotifyProgressCaptureWideRawLiveStacking& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyProgressCaptureWideRawLiveStacking* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 current_count = 1;
  void clear_current_count();
  static const int kCurrentCountFieldNumber = 1;
  ::google::protobuf::int32 current_count() const;
  void set_current_count(::google::protobuf::int32 value);

  // int32 total_count = 2;
  void clear_total_count();
  static const int kTotalCountFieldNumber = 2;
  ::google::protobuf::int32 total_count() const;
  void set_total_count(::google::protobuf::int32 value);

  // int32 stacked_count = 3;
  void clear_stacked_count();
  static const int kStackedCountFieldNumber = 3;
  ::google::protobuf::int32 stacked_count() const;
  void set_stacked_count(::google::protobuf::int32 value);

  // int32 rejected_count = 4;
  void clear_rejected_count();
  static const int kRejectedCountFieldNumber = 4;
  ::google::protobuf::int32 rejected_count() const;
  void set_rejected_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyProgressCaptureWideRawLiveStacking)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 current_count_;
  ::google::protobuf::int32 total_count_;
  ::google::protobuf::int32 stacked_count_;
  ::google::protobuf::int32 rejected_count_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyEqSolvingState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyEqSolvingState) */ {
 public:
  ResNotifyEqSolvingState();
  virtual ~ResNotifyEqSolvingState();

  ResNotifyEqSolvingState(const ResNotifyEqSolvingState& from);

  inline ResNotifyEqSolvingState& operator=(const ResNotifyEqSolvingState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyEqSolvingState(ResNotifyEqSolvingState&& from) noexcept
    : ResNotifyEqSolvingState() {
    *this = ::std::move(from);
  }

  inline ResNotifyEqSolvingState& operator=(ResNotifyEqSolvingState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyEqSolvingState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyEqSolvingState* internal_default_instance() {
    return reinterpret_cast<const ResNotifyEqSolvingState*>(
               &_ResNotifyEqSolvingState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    13;

  void Swap(ResNotifyEqSolvingState* other);
  friend void swap(ResNotifyEqSolvingState& a, ResNotifyEqSolvingState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyEqSolvingState* New() const final {
    return CreateMaybeMessage<ResNotifyEqSolvingState>(NULL);
  }

  ResNotifyEqSolvingState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyEqSolvingState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyEqSolvingState& from);
  void MergeFrom(const ResNotifyEqSolvingState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyEqSolvingState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double azi_err = 2;
  void clear_azi_err();
  static const int kAziErrFieldNumber = 2;
  double azi_err() const;
  void set_azi_err(double value);

  // double alt_err = 3;
  void clear_alt_err();
  static const int kAltErrFieldNumber = 3;
  double alt_err() const;
  void set_alt_err(double value);

  // int32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyEqSolvingState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double azi_err_;
  double alt_err_;
  ::google::protobuf::int32 state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyTemperature : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyTemperature) */ {
 public:
  ResNotifyTemperature();
  virtual ~ResNotifyTemperature();

  ResNotifyTemperature(const ResNotifyTemperature& from);

  inline ResNotifyTemperature& operator=(const ResNotifyTemperature& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyTemperature(ResNotifyTemperature&& from) noexcept
    : ResNotifyTemperature() {
    *this = ::std::move(from);
  }

  inline ResNotifyTemperature& operator=(ResNotifyTemperature&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyTemperature& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyTemperature* internal_default_instance() {
    return reinterpret_cast<const ResNotifyTemperature*>(
               &_ResNotifyTemperature_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    14;

  void Swap(ResNotifyTemperature* other);
  friend void swap(ResNotifyTemperature& a, ResNotifyTemperature& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyTemperature* New() const final {
    return CreateMaybeMessage<ResNotifyTemperature>(NULL);
  }

  ResNotifyTemperature* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyTemperature>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyTemperature& from);
  void MergeFrom(const ResNotifyTemperature& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyTemperature* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 temperature = 1;
  void clear_temperature();
  static const int kTemperatureFieldNumber = 1;
  ::google::protobuf::int32 temperature() const;
  void set_temperature(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyTemperature)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 temperature_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResNotifyFocus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ResNotifyFocus) */ {
 public:
  ResNotifyFocus();
  virtual ~ResNotifyFocus();

  ResNotifyFocus(const ResNotifyFocus& from);

  inline ResNotifyFocus& operator=(const ResNotifyFocus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResNotifyFocus(ResNotifyFocus&& from) noexcept
    : ResNotifyFocus() {
    *this = ::std::move(from);
  }

  inline ResNotifyFocus& operator=(ResNotifyFocus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResNotifyFocus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResNotifyFocus* internal_default_instance() {
    return reinterpret_cast<const ResNotifyFocus*>(
               &_ResNotifyFocus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    15;

  void Swap(ResNotifyFocus* other);
  friend void swap(ResNotifyFocus& a, ResNotifyFocus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResNotifyFocus* New() const final {
    return CreateMaybeMessage<ResNotifyFocus>(NULL);
  }

  ResNotifyFocus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResNotifyFocus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResNotifyFocus& from);
  void MergeFrom(const ResNotifyFocus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResNotifyFocus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 position = 1;
  void clear_position();
  static const int kPositionFieldNumber = 1;
  ::google::protobuf::int32 position() const;
  void set_position(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ResNotifyFocus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 position_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_notify_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResNotifyBattery

// int32 value = 1;
inline void ResNotifyBattery::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 ResNotifyBattery::value() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyBattery.value)
  return value_;
}
inline void ResNotifyBattery::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyBattery.value)
}

// -------------------------------------------------------------------

// ResNotifyChargeStatus

// int32 value = 1;
inline void ResNotifyChargeStatus::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 ResNotifyChargeStatus::value() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyChargeStatus.value)
  return value_;
}
inline void ResNotifyChargeStatus::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyChargeStatus.value)
}

// -------------------------------------------------------------------

// ResNotifySDcardInfo

// int64 total = 1;
inline void ResNotifySDcardInfo::clear_total() {
  total_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ResNotifySDcardInfo::total() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifySDcardInfo.total)
  return total_;
}
inline void ResNotifySDcardInfo::set_total(::google::protobuf::int64 value) {
  
  total_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifySDcardInfo.total)
}

// int64 available = 2;
inline void ResNotifySDcardInfo::clear_available() {
  available_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ResNotifySDcardInfo::available() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifySDcardInfo.available)
  return available_;
}
inline void ResNotifySDcardInfo::set_available(::google::protobuf::int64 value) {
  
  available_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifySDcardInfo.available)
}

// -------------------------------------------------------------------

// ResNotifyDarkOperationState

// int32 state = 1;
inline void ResNotifyDarkOperationState::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 ResNotifyDarkOperationState::state() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyDarkOperationState.state)
  return state_;
}
inline void ResNotifyDarkOperationState::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyDarkOperationState.state)
}

// -------------------------------------------------------------------

// ResNotifyProgressCaptureRawDark

// int32 current_count = 1;
inline void ResNotifyProgressCaptureRawDark::clear_current_count() {
  current_count_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureRawDark::current_count() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureRawDark.current_count)
  return current_count_;
}
inline void ResNotifyProgressCaptureRawDark::set_current_count(::google::protobuf::int32 value) {
  
  current_count_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureRawDark.current_count)
}

// int32 total_count = 2;
inline void ResNotifyProgressCaptureRawDark::clear_total_count() {
  total_count_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureRawDark::total_count() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureRawDark.total_count)
  return total_count_;
}
inline void ResNotifyProgressCaptureRawDark::set_total_count(::google::protobuf::int32 value) {
  
  total_count_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureRawDark.total_count)
}

// -------------------------------------------------------------------

// ResNotifyOperationState

// int32 state = 1;
inline void ResNotifyOperationState::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 ResNotifyOperationState::state() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyOperationState.state)
  return state_;
}
inline void ResNotifyOperationState::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyOperationState.state)
}

// -------------------------------------------------------------------

// ResNotifyProgressCaptureRawLiveStacking

// int32 current_count = 1;
inline void ResNotifyProgressCaptureRawLiveStacking::clear_current_count() {
  current_count_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureRawLiveStacking::current_count() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureRawLiveStacking.current_count)
  return current_count_;
}
inline void ResNotifyProgressCaptureRawLiveStacking::set_current_count(::google::protobuf::int32 value) {
  
  current_count_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureRawLiveStacking.current_count)
}

// int32 total_count = 2;
inline void ResNotifyProgressCaptureRawLiveStacking::clear_total_count() {
  total_count_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureRawLiveStacking::total_count() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureRawLiveStacking.total_count)
  return total_count_;
}
inline void ResNotifyProgressCaptureRawLiveStacking::set_total_count(::google::protobuf::int32 value) {
  
  total_count_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureRawLiveStacking.total_count)
}

// int32 stacked_count = 3;
inline void ResNotifyProgressCaptureRawLiveStacking::clear_stacked_count() {
  stacked_count_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureRawLiveStacking::stacked_count() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureRawLiveStacking.stacked_count)
  return stacked_count_;
}
inline void ResNotifyProgressCaptureRawLiveStacking::set_stacked_count(::google::protobuf::int32 value) {
  
  stacked_count_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureRawLiveStacking.stacked_count)
}

// int32 rejected_count = 4;
inline void ResNotifyProgressCaptureRawLiveStacking::clear_rejected_count() {
  rejected_count_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureRawLiveStacking::rejected_count() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureRawLiveStacking.rejected_count)
  return rejected_count_;
}
inline void ResNotifyProgressCaptureRawLiveStacking::set_rejected_count(::google::protobuf::int32 value) {
  
  rejected_count_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureRawLiveStacking.rejected_count)
}

// int32 exp_index = 5;
inline void ResNotifyProgressCaptureRawLiveStacking::clear_exp_index() {
  exp_index_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureRawLiveStacking::exp_index() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureRawLiveStacking.exp_index)
  return exp_index_;
}
inline void ResNotifyProgressCaptureRawLiveStacking::set_exp_index(::google::protobuf::int32 value) {
  
  exp_index_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureRawLiveStacking.exp_index)
}

// int32 gain_index = 6;
inline void ResNotifyProgressCaptureRawLiveStacking::clear_gain_index() {
  gain_index_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureRawLiveStacking::gain_index() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureRawLiveStacking.gain_index)
  return gain_index_;
}
inline void ResNotifyProgressCaptureRawLiveStacking::set_gain_index(::google::protobuf::int32 value) {
  
  gain_index_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureRawLiveStacking.gain_index)
}

// int32 bin_index = 7;
inline void ResNotifyProgressCaptureRawLiveStacking::clear_bin_index() {
  bin_index_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureRawLiveStacking::bin_index() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureRawLiveStacking.bin_index)
  return bin_index_;
}
inline void ResNotifyProgressCaptureRawLiveStacking::set_bin_index(::google::protobuf::int32 value) {
  
  bin_index_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureRawLiveStacking.bin_index)
}

// -------------------------------------------------------------------

// ResNotifyStateAstroCalibration

// int32 state = 1;
inline void ResNotifyStateAstroCalibration::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 ResNotifyStateAstroCalibration::state() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyStateAstroCalibration.state)
  return state_;
}
inline void ResNotifyStateAstroCalibration::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyStateAstroCalibration.state)
}

// int32 code = 2;
inline void ResNotifyStateAstroCalibration::clear_code() {
  code_ = 0;
}
inline ::google::protobuf::int32 ResNotifyStateAstroCalibration::code() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyStateAstroCalibration.code)
  return code_;
}
inline void ResNotifyStateAstroCalibration::set_code(::google::protobuf::int32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyStateAstroCalibration.code)
}

// -------------------------------------------------------------------

// ResNotifyStateAstroGoto

// int32 state = 1;
inline void ResNotifyStateAstroGoto::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 ResNotifyStateAstroGoto::state() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyStateAstroGoto.state)
  return state_;
}
inline void ResNotifyStateAstroGoto::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyStateAstroGoto.state)
}

// int32 code = 2;
inline void ResNotifyStateAstroGoto::clear_code() {
  code_ = 0;
}
inline ::google::protobuf::int32 ResNotifyStateAstroGoto::code() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyStateAstroGoto.code)
  return code_;
}
inline void ResNotifyStateAstroGoto::set_code(::google::protobuf::int32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyStateAstroGoto.code)
}

// -------------------------------------------------------------------

// ResNotifyStateAstroTracking

// int32 state = 1;
inline void ResNotifyStateAstroTracking::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 ResNotifyStateAstroTracking::state() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyStateAstroTracking.state)
  return state_;
}
inline void ResNotifyStateAstroTracking::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyStateAstroTracking.state)
}

// -------------------------------------------------------------------

// ResNotifyOneClickGotoState

// int32 step = 1;
inline void ResNotifyOneClickGotoState::clear_step() {
  step_ = 0;
}
inline ::google::protobuf::int32 ResNotifyOneClickGotoState::step() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyOneClickGotoState.step)
  return step_;
}
inline void ResNotifyOneClickGotoState::set_step(::google::protobuf::int32 value) {
  
  step_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyOneClickGotoState.step)
}

// int32 state = 2;
inline void ResNotifyOneClickGotoState::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 ResNotifyOneClickGotoState::state() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyOneClickGotoState.state)
  return state_;
}
inline void ResNotifyOneClickGotoState::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyOneClickGotoState.state)
}

// int32 code = 3;
inline void ResNotifyOneClickGotoState::clear_code() {
  code_ = 0;
}
inline ::google::protobuf::int32 ResNotifyOneClickGotoState::code() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyOneClickGotoState.code)
  return code_;
}
inline void ResNotifyOneClickGotoState::set_code(::google::protobuf::int32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyOneClickGotoState.code)
}

// -------------------------------------------------------------------

// ResNotifyWideOperationState

// int32 state = 1;
inline void ResNotifyWideOperationState::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 ResNotifyWideOperationState::state() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyWideOperationState.state)
  return state_;
}
inline void ResNotifyWideOperationState::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyWideOperationState.state)
}

// -------------------------------------------------------------------

// ResNotifyProgressCaptureWideRawLiveStacking

// int32 current_count = 1;
inline void ResNotifyProgressCaptureWideRawLiveStacking::clear_current_count() {
  current_count_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureWideRawLiveStacking::current_count() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureWideRawLiveStacking.current_count)
  return current_count_;
}
inline void ResNotifyProgressCaptureWideRawLiveStacking::set_current_count(::google::protobuf::int32 value) {
  
  current_count_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureWideRawLiveStacking.current_count)
}

// int32 total_count = 2;
inline void ResNotifyProgressCaptureWideRawLiveStacking::clear_total_count() {
  total_count_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureWideRawLiveStacking::total_count() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureWideRawLiveStacking.total_count)
  return total_count_;
}
inline void ResNotifyProgressCaptureWideRawLiveStacking::set_total_count(::google::protobuf::int32 value) {
  
  total_count_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureWideRawLiveStacking.total_count)
}

// int32 stacked_count = 3;
inline void ResNotifyProgressCaptureWideRawLiveStacking::clear_stacked_count() {
  stacked_count_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureWideRawLiveStacking::stacked_count() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureWideRawLiveStacking.stacked_count)
  return stacked_count_;
}
inline void ResNotifyProgressCaptureWideRawLiveStacking::set_stacked_count(::google::protobuf::int32 value) {
  
  stacked_count_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureWideRawLiveStacking.stacked_count)
}

// int32 rejected_count = 4;
inline void ResNotifyProgressCaptureWideRawLiveStacking::clear_rejected_count() {
  rejected_count_ = 0;
}
inline ::google::protobuf::int32 ResNotifyProgressCaptureWideRawLiveStacking::rejected_count() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyProgressCaptureWideRawLiveStacking.rejected_count)
  return rejected_count_;
}
inline void ResNotifyProgressCaptureWideRawLiveStacking::set_rejected_count(::google::protobuf::int32 value) {
  
  rejected_count_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyProgressCaptureWideRawLiveStacking.rejected_count)
}

// -------------------------------------------------------------------

// ResNotifyEqSolvingState

// int32 state = 1;
inline void ResNotifyEqSolvingState::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 ResNotifyEqSolvingState::state() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyEqSolvingState.state)
  return state_;
}
inline void ResNotifyEqSolvingState::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyEqSolvingState.state)
}

// double azi_err = 2;
inline void ResNotifyEqSolvingState::clear_azi_err() {
  azi_err_ = 0;
}
inline double ResNotifyEqSolvingState::azi_err() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyEqSolvingState.azi_err)
  return azi_err_;
}
inline void ResNotifyEqSolvingState::set_azi_err(double value) {
  
  azi_err_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyEqSolvingState.azi_err)
}

// double alt_err = 3;
inline void ResNotifyEqSolvingState::clear_alt_err() {
  alt_err_ = 0;
}
inline double ResNotifyEqSolvingState::alt_err() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyEqSolvingState.alt_err)
  return alt_err_;
}
inline void ResNotifyEqSolvingState::set_alt_err(double value) {
  
  alt_err_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyEqSolvingState.alt_err)
}

// -------------------------------------------------------------------

// ResNotifyTemperature

// int32 temperature = 1;
inline void ResNotifyTemperature::clear_temperature() {
  temperature_ = 0;
}
inline ::google::protobuf::int32 ResNotifyTemperature::temperature() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyTemperature.temperature)
  return temperature_;
}
inline void ResNotifyTemperature::set_temperature(::google::protobuf::int32 value) {
  
  temperature_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyTemperature.temperature)
}

// -------------------------------------------------------------------

// ResNotifyFocus

// int32 position = 1;
inline void ResNotifyFocus::clear_position() {
  position_ = 0;
}
inline ::google::protobuf::int32 ResNotifyFocus::position() const {
  // @@protoc_insertion_point(field_get:dwarf.ResNotifyFocus.position)
  return position_;
}
inline void ResNotifyFocus::set_position(::google::protobuf::int32 value) {
  
  position_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ResNotifyFocus.position)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dwarf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_notify_2eproto
