// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: panorama.proto

#include "panorama.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace dwarf {
class ReqStartPanoramaByGridDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqStartPanoramaByGrid>
      _instance;
} _ReqStartPanoramaByGrid_default_instance_;
class ReqStopPanoramaDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqStopPanorama>
      _instance;
} _ReqStopPanorama_default_instance_;
class ResNotifyPanoramaProgressDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResNotifyPanoramaProgress>
      _instance;
} _ResNotifyPanoramaProgress_default_instance_;
}  // namespace dwarf
namespace protobuf_panorama_2eproto {
static void InitDefaultsReqStartPanoramaByGrid() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqStartPanoramaByGrid_default_instance_;
    new (ptr) ::dwarf::ReqStartPanoramaByGrid();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqStartPanoramaByGrid::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqStartPanoramaByGrid =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqStartPanoramaByGrid}, {}};

static void InitDefaultsReqStopPanorama() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqStopPanorama_default_instance_;
    new (ptr) ::dwarf::ReqStopPanorama();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqStopPanorama::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqStopPanorama =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqStopPanorama}, {}};

static void InitDefaultsResNotifyPanoramaProgress() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ResNotifyPanoramaProgress_default_instance_;
    new (ptr) ::dwarf::ResNotifyPanoramaProgress();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ResNotifyPanoramaProgress::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ResNotifyPanoramaProgress =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsResNotifyPanoramaProgress}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ReqStartPanoramaByGrid.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqStopPanorama.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ResNotifyPanoramaProgress.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, rows_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, cols_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, mstep1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, mstep2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, speed1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, speed2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, pulse1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, pulse2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, accelstep1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartPanoramaByGrid, accelstep2_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStopPanorama, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ResNotifyPanoramaProgress, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ResNotifyPanoramaProgress, total_count_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ResNotifyPanoramaProgress, completed_count_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::dwarf::ReqStartPanoramaByGrid)},
  { 15, -1, sizeof(::dwarf::ReqStopPanorama)},
  { 20, -1, sizeof(::dwarf::ResNotifyPanoramaProgress)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqStartPanoramaByGrid_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqStopPanorama_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ResNotifyPanoramaProgress_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "panorama.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016panorama.proto\022\005dwarf\"\274\001\n\026ReqStartPano"
      "ramaByGrid\022\014\n\004rows\030\001 \001(\r\022\014\n\004cols\030\002 \001(\r\022\016"
      "\n\006mStep1\030\003 \001(\r\022\016\n\006mStep2\030\004 \001(\r\022\016\n\006speed1"
      "\030\005 \001(\r\022\016\n\006speed2\030\006 \001(\r\022\016\n\006pulse1\030\007 \001(\r\022\016"
      "\n\006pulse2\030\010 \001(\r\022\022\n\naccelStep1\030\t \001(\r\022\022\n\nac"
      "celStep2\030\n \001(\r\"\021\n\017ReqStopPanorama\"I\n\031Res"
      "NotifyPanoramaProgress\022\023\n\013total_count\030\001 "
      "\001(\005\022\027\n\017completed_count\030\002 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 316);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "panorama.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_panorama_2eproto
namespace dwarf {

// ===================================================================

void ReqStartPanoramaByGrid::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqStartPanoramaByGrid::kRowsFieldNumber;
const int ReqStartPanoramaByGrid::kColsFieldNumber;
const int ReqStartPanoramaByGrid::kMStep1FieldNumber;
const int ReqStartPanoramaByGrid::kMStep2FieldNumber;
const int ReqStartPanoramaByGrid::kSpeed1FieldNumber;
const int ReqStartPanoramaByGrid::kSpeed2FieldNumber;
const int ReqStartPanoramaByGrid::kPulse1FieldNumber;
const int ReqStartPanoramaByGrid::kPulse2FieldNumber;
const int ReqStartPanoramaByGrid::kAccelStep1FieldNumber;
const int ReqStartPanoramaByGrid::kAccelStep2FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqStartPanoramaByGrid::ReqStartPanoramaByGrid()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_panorama_2eproto::scc_info_ReqStartPanoramaByGrid.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqStartPanoramaByGrid)
}
ReqStartPanoramaByGrid::ReqStartPanoramaByGrid(const ReqStartPanoramaByGrid& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&rows_, &from.rows_,
    static_cast<size_t>(reinterpret_cast<char*>(&accelstep2_) -
    reinterpret_cast<char*>(&rows_)) + sizeof(accelstep2_));
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqStartPanoramaByGrid)
}

void ReqStartPanoramaByGrid::SharedCtor() {
  ::memset(&rows_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&accelstep2_) -
      reinterpret_cast<char*>(&rows_)) + sizeof(accelstep2_));
}

ReqStartPanoramaByGrid::~ReqStartPanoramaByGrid() {
  // @@protoc_insertion_point(destructor:dwarf.ReqStartPanoramaByGrid)
  SharedDtor();
}

void ReqStartPanoramaByGrid::SharedDtor() {
}

void ReqStartPanoramaByGrid::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqStartPanoramaByGrid::descriptor() {
  ::protobuf_panorama_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_panorama_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqStartPanoramaByGrid& ReqStartPanoramaByGrid::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_panorama_2eproto::scc_info_ReqStartPanoramaByGrid.base);
  return *internal_default_instance();
}


void ReqStartPanoramaByGrid::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqStartPanoramaByGrid)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&rows_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&accelstep2_) -
      reinterpret_cast<char*>(&rows_)) + sizeof(accelstep2_));
  _internal_metadata_.Clear();
}

bool ReqStartPanoramaByGrid::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqStartPanoramaByGrid)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 rows = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &rows_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 cols = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &cols_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 mStep1 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &mstep1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 mStep2 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &mstep2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 speed1 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &speed1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 speed2 = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &speed2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 pulse1 = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &pulse1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 pulse2 = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &pulse2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 accelStep1 = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &accelstep1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 accelStep2 = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &accelstep2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqStartPanoramaByGrid)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqStartPanoramaByGrid)
  return false;
#undef DO_
}

void ReqStartPanoramaByGrid::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqStartPanoramaByGrid)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 rows = 1;
  if (this->rows() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->rows(), output);
  }

  // uint32 cols = 2;
  if (this->cols() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->cols(), output);
  }

  // uint32 mStep1 = 3;
  if (this->mstep1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->mstep1(), output);
  }

  // uint32 mStep2 = 4;
  if (this->mstep2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->mstep2(), output);
  }

  // uint32 speed1 = 5;
  if (this->speed1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->speed1(), output);
  }

  // uint32 speed2 = 6;
  if (this->speed2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->speed2(), output);
  }

  // uint32 pulse1 = 7;
  if (this->pulse1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->pulse1(), output);
  }

  // uint32 pulse2 = 8;
  if (this->pulse2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->pulse2(), output);
  }

  // uint32 accelStep1 = 9;
  if (this->accelstep1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->accelstep1(), output);
  }

  // uint32 accelStep2 = 10;
  if (this->accelstep2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->accelstep2(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqStartPanoramaByGrid)
}

::google::protobuf::uint8* ReqStartPanoramaByGrid::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqStartPanoramaByGrid)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 rows = 1;
  if (this->rows() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->rows(), target);
  }

  // uint32 cols = 2;
  if (this->cols() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->cols(), target);
  }

  // uint32 mStep1 = 3;
  if (this->mstep1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->mstep1(), target);
  }

  // uint32 mStep2 = 4;
  if (this->mstep2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->mstep2(), target);
  }

  // uint32 speed1 = 5;
  if (this->speed1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->speed1(), target);
  }

  // uint32 speed2 = 6;
  if (this->speed2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->speed2(), target);
  }

  // uint32 pulse1 = 7;
  if (this->pulse1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->pulse1(), target);
  }

  // uint32 pulse2 = 8;
  if (this->pulse2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->pulse2(), target);
  }

  // uint32 accelStep1 = 9;
  if (this->accelstep1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->accelstep1(), target);
  }

  // uint32 accelStep2 = 10;
  if (this->accelstep2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(10, this->accelstep2(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqStartPanoramaByGrid)
  return target;
}

size_t ReqStartPanoramaByGrid::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqStartPanoramaByGrid)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 rows = 1;
  if (this->rows() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->rows());
  }

  // uint32 cols = 2;
  if (this->cols() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->cols());
  }

  // uint32 mStep1 = 3;
  if (this->mstep1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->mstep1());
  }

  // uint32 mStep2 = 4;
  if (this->mstep2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->mstep2());
  }

  // uint32 speed1 = 5;
  if (this->speed1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->speed1());
  }

  // uint32 speed2 = 6;
  if (this->speed2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->speed2());
  }

  // uint32 pulse1 = 7;
  if (this->pulse1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->pulse1());
  }

  // uint32 pulse2 = 8;
  if (this->pulse2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->pulse2());
  }

  // uint32 accelStep1 = 9;
  if (this->accelstep1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->accelstep1());
  }

  // uint32 accelStep2 = 10;
  if (this->accelstep2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->accelstep2());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqStartPanoramaByGrid::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqStartPanoramaByGrid)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqStartPanoramaByGrid* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqStartPanoramaByGrid>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqStartPanoramaByGrid)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqStartPanoramaByGrid)
    MergeFrom(*source);
  }
}

void ReqStartPanoramaByGrid::MergeFrom(const ReqStartPanoramaByGrid& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqStartPanoramaByGrid)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.rows() != 0) {
    set_rows(from.rows());
  }
  if (from.cols() != 0) {
    set_cols(from.cols());
  }
  if (from.mstep1() != 0) {
    set_mstep1(from.mstep1());
  }
  if (from.mstep2() != 0) {
    set_mstep2(from.mstep2());
  }
  if (from.speed1() != 0) {
    set_speed1(from.speed1());
  }
  if (from.speed2() != 0) {
    set_speed2(from.speed2());
  }
  if (from.pulse1() != 0) {
    set_pulse1(from.pulse1());
  }
  if (from.pulse2() != 0) {
    set_pulse2(from.pulse2());
  }
  if (from.accelstep1() != 0) {
    set_accelstep1(from.accelstep1());
  }
  if (from.accelstep2() != 0) {
    set_accelstep2(from.accelstep2());
  }
}

void ReqStartPanoramaByGrid::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqStartPanoramaByGrid)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqStartPanoramaByGrid::CopyFrom(const ReqStartPanoramaByGrid& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqStartPanoramaByGrid)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqStartPanoramaByGrid::IsInitialized() const {
  return true;
}

void ReqStartPanoramaByGrid::Swap(ReqStartPanoramaByGrid* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqStartPanoramaByGrid::InternalSwap(ReqStartPanoramaByGrid* other) {
  using std::swap;
  swap(rows_, other->rows_);
  swap(cols_, other->cols_);
  swap(mstep1_, other->mstep1_);
  swap(mstep2_, other->mstep2_);
  swap(speed1_, other->speed1_);
  swap(speed2_, other->speed2_);
  swap(pulse1_, other->pulse1_);
  swap(pulse2_, other->pulse2_);
  swap(accelstep1_, other->accelstep1_);
  swap(accelstep2_, other->accelstep2_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqStartPanoramaByGrid::GetMetadata() const {
  protobuf_panorama_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_panorama_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqStopPanorama::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqStopPanorama::ReqStopPanorama()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_panorama_2eproto::scc_info_ReqStopPanorama.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqStopPanorama)
}
ReqStopPanorama::ReqStopPanorama(const ReqStopPanorama& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqStopPanorama)
}

void ReqStopPanorama::SharedCtor() {
}

ReqStopPanorama::~ReqStopPanorama() {
  // @@protoc_insertion_point(destructor:dwarf.ReqStopPanorama)
  SharedDtor();
}

void ReqStopPanorama::SharedDtor() {
}

void ReqStopPanorama::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqStopPanorama::descriptor() {
  ::protobuf_panorama_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_panorama_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqStopPanorama& ReqStopPanorama::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_panorama_2eproto::scc_info_ReqStopPanorama.base);
  return *internal_default_instance();
}


void ReqStopPanorama::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqStopPanorama)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool ReqStopPanorama::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqStopPanorama)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqStopPanorama)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqStopPanorama)
  return false;
#undef DO_
}

void ReqStopPanorama::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqStopPanorama)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqStopPanorama)
}

::google::protobuf::uint8* ReqStopPanorama::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqStopPanorama)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqStopPanorama)
  return target;
}

size_t ReqStopPanorama::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqStopPanorama)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqStopPanorama::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqStopPanorama)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqStopPanorama* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqStopPanorama>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqStopPanorama)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqStopPanorama)
    MergeFrom(*source);
  }
}

void ReqStopPanorama::MergeFrom(const ReqStopPanorama& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqStopPanorama)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ReqStopPanorama::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqStopPanorama)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqStopPanorama::CopyFrom(const ReqStopPanorama& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqStopPanorama)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqStopPanorama::IsInitialized() const {
  return true;
}

void ReqStopPanorama::Swap(ReqStopPanorama* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqStopPanorama::InternalSwap(ReqStopPanorama* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqStopPanorama::GetMetadata() const {
  protobuf_panorama_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_panorama_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ResNotifyPanoramaProgress::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResNotifyPanoramaProgress::kTotalCountFieldNumber;
const int ResNotifyPanoramaProgress::kCompletedCountFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResNotifyPanoramaProgress::ResNotifyPanoramaProgress()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_panorama_2eproto::scc_info_ResNotifyPanoramaProgress.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ResNotifyPanoramaProgress)
}
ResNotifyPanoramaProgress::ResNotifyPanoramaProgress(const ResNotifyPanoramaProgress& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&total_count_, &from.total_count_,
    static_cast<size_t>(reinterpret_cast<char*>(&completed_count_) -
    reinterpret_cast<char*>(&total_count_)) + sizeof(completed_count_));
  // @@protoc_insertion_point(copy_constructor:dwarf.ResNotifyPanoramaProgress)
}

void ResNotifyPanoramaProgress::SharedCtor() {
  ::memset(&total_count_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&completed_count_) -
      reinterpret_cast<char*>(&total_count_)) + sizeof(completed_count_));
}

ResNotifyPanoramaProgress::~ResNotifyPanoramaProgress() {
  // @@protoc_insertion_point(destructor:dwarf.ResNotifyPanoramaProgress)
  SharedDtor();
}

void ResNotifyPanoramaProgress::SharedDtor() {
}

void ResNotifyPanoramaProgress::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ResNotifyPanoramaProgress::descriptor() {
  ::protobuf_panorama_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_panorama_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResNotifyPanoramaProgress& ResNotifyPanoramaProgress::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_panorama_2eproto::scc_info_ResNotifyPanoramaProgress.base);
  return *internal_default_instance();
}


void ResNotifyPanoramaProgress::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ResNotifyPanoramaProgress)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&total_count_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&completed_count_) -
      reinterpret_cast<char*>(&total_count_)) + sizeof(completed_count_));
  _internal_metadata_.Clear();
}

bool ResNotifyPanoramaProgress::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ResNotifyPanoramaProgress)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 total_count = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &total_count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 completed_count = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &completed_count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ResNotifyPanoramaProgress)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ResNotifyPanoramaProgress)
  return false;
#undef DO_
}

void ResNotifyPanoramaProgress::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ResNotifyPanoramaProgress)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 total_count = 1;
  if (this->total_count() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->total_count(), output);
  }

  // int32 completed_count = 2;
  if (this->completed_count() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->completed_count(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ResNotifyPanoramaProgress)
}

::google::protobuf::uint8* ResNotifyPanoramaProgress::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ResNotifyPanoramaProgress)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 total_count = 1;
  if (this->total_count() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->total_count(), target);
  }

  // int32 completed_count = 2;
  if (this->completed_count() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->completed_count(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ResNotifyPanoramaProgress)
  return target;
}

size_t ResNotifyPanoramaProgress::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ResNotifyPanoramaProgress)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 total_count = 1;
  if (this->total_count() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->total_count());
  }

  // int32 completed_count = 2;
  if (this->completed_count() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->completed_count());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResNotifyPanoramaProgress::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ResNotifyPanoramaProgress)
  GOOGLE_DCHECK_NE(&from, this);
  const ResNotifyPanoramaProgress* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResNotifyPanoramaProgress>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ResNotifyPanoramaProgress)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ResNotifyPanoramaProgress)
    MergeFrom(*source);
  }
}

void ResNotifyPanoramaProgress::MergeFrom(const ResNotifyPanoramaProgress& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ResNotifyPanoramaProgress)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.total_count() != 0) {
    set_total_count(from.total_count());
  }
  if (from.completed_count() != 0) {
    set_completed_count(from.completed_count());
  }
}

void ResNotifyPanoramaProgress::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ResNotifyPanoramaProgress)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResNotifyPanoramaProgress::CopyFrom(const ResNotifyPanoramaProgress& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ResNotifyPanoramaProgress)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResNotifyPanoramaProgress::IsInitialized() const {
  return true;
}

void ResNotifyPanoramaProgress::Swap(ResNotifyPanoramaProgress* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResNotifyPanoramaProgress::InternalSwap(ResNotifyPanoramaProgress* other) {
  using std::swap;
  swap(total_count_, other->total_count_);
  swap(completed_count_, other->completed_count_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ResNotifyPanoramaProgress::GetMetadata() const {
  protobuf_panorama_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_panorama_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace dwarf
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqStartPanoramaByGrid* Arena::CreateMaybeMessage< ::dwarf::ReqStartPanoramaByGrid >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqStartPanoramaByGrid >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqStopPanorama* Arena::CreateMaybeMessage< ::dwarf::ReqStopPanorama >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqStopPanorama >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ResNotifyPanoramaProgress* Arena::CreateMaybeMessage< ::dwarf::ResNotifyPanoramaProgress >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ResNotifyPanoramaProgress >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
