// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

#ifndef PROTOBUF_INCLUDED_tracking_2eproto
#define PROTOBUF_INCLUDED_tracking_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_tracking_2eproto 

namespace protobuf_tracking_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_tracking_2eproto
namespace dwarf {
class ReqMOTStart;
class ReqMOTStartDefaultTypeInternal;
extern ReqMOTStartDefaultTypeInternal _ReqMOTStart_default_instance_;
class ReqMOTTrackOne;
class ReqMOTTrackOneDefaultTypeInternal;
extern ReqMOTTrackOneDefaultTypeInternal _ReqMOTTrackOne_default_instance_;
class ReqStartSentryMode;
class ReqStartSentryModeDefaultTypeInternal;
extern ReqStartSentryModeDefaultTypeInternal _ReqStartSentryMode_default_instance_;
class ReqStartTrack;
class ReqStartTrackDefaultTypeInternal;
extern ReqStartTrackDefaultTypeInternal _ReqStartTrack_default_instance_;
class ReqStopSentryMode;
class ReqStopSentryModeDefaultTypeInternal;
extern ReqStopSentryModeDefaultTypeInternal _ReqStopSentryMode_default_instance_;
class ReqStopTrack;
class ReqStopTrackDefaultTypeInternal;
extern ReqStopTrackDefaultTypeInternal _ReqStopTrack_default_instance_;
}  // namespace dwarf
namespace google {
namespace protobuf {
template<> ::dwarf::ReqMOTStart* Arena::CreateMaybeMessage<::dwarf::ReqMOTStart>(Arena*);
template<> ::dwarf::ReqMOTTrackOne* Arena::CreateMaybeMessage<::dwarf::ReqMOTTrackOne>(Arena*);
template<> ::dwarf::ReqStartSentryMode* Arena::CreateMaybeMessage<::dwarf::ReqStartSentryMode>(Arena*);
template<> ::dwarf::ReqStartTrack* Arena::CreateMaybeMessage<::dwarf::ReqStartTrack>(Arena*);
template<> ::dwarf::ReqStopSentryMode* Arena::CreateMaybeMessage<::dwarf::ReqStopSentryMode>(Arena*);
template<> ::dwarf::ReqStopTrack* Arena::CreateMaybeMessage<::dwarf::ReqStopTrack>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace dwarf {

// ===================================================================

class ReqStartTrack : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqStartTrack) */ {
 public:
  ReqStartTrack();
  virtual ~ReqStartTrack();

  ReqStartTrack(const ReqStartTrack& from);

  inline ReqStartTrack& operator=(const ReqStartTrack& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqStartTrack(ReqStartTrack&& from) noexcept
    : ReqStartTrack() {
    *this = ::std::move(from);
  }

  inline ReqStartTrack& operator=(ReqStartTrack&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqStartTrack& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqStartTrack* internal_default_instance() {
    return reinterpret_cast<const ReqStartTrack*>(
               &_ReqStartTrack_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ReqStartTrack* other);
  friend void swap(ReqStartTrack& a, ReqStartTrack& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqStartTrack* New() const final {
    return CreateMaybeMessage<ReqStartTrack>(NULL);
  }

  ReqStartTrack* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqStartTrack>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqStartTrack& from);
  void MergeFrom(const ReqStartTrack& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqStartTrack* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // int32 y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // int32 w = 3;
  void clear_w();
  static const int kWFieldNumber = 3;
  ::google::protobuf::int32 w() const;
  void set_w(::google::protobuf::int32 value);

  // int32 h = 4;
  void clear_h();
  static const int kHFieldNumber = 4;
  ::google::protobuf::int32 h() const;
  void set_h(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ReqStartTrack)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::google::protobuf::int32 w_;
  ::google::protobuf::int32 h_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tracking_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqStopTrack : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqStopTrack) */ {
 public:
  ReqStopTrack();
  virtual ~ReqStopTrack();

  ReqStopTrack(const ReqStopTrack& from);

  inline ReqStopTrack& operator=(const ReqStopTrack& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqStopTrack(ReqStopTrack&& from) noexcept
    : ReqStopTrack() {
    *this = ::std::move(from);
  }

  inline ReqStopTrack& operator=(ReqStopTrack&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqStopTrack& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqStopTrack* internal_default_instance() {
    return reinterpret_cast<const ReqStopTrack*>(
               &_ReqStopTrack_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ReqStopTrack* other);
  friend void swap(ReqStopTrack& a, ReqStopTrack& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqStopTrack* New() const final {
    return CreateMaybeMessage<ReqStopTrack>(NULL);
  }

  ReqStopTrack* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqStopTrack>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqStopTrack& from);
  void MergeFrom(const ReqStopTrack& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqStopTrack* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:dwarf.ReqStopTrack)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tracking_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqStartSentryMode : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqStartSentryMode) */ {
 public:
  ReqStartSentryMode();
  virtual ~ReqStartSentryMode();

  ReqStartSentryMode(const ReqStartSentryMode& from);

  inline ReqStartSentryMode& operator=(const ReqStartSentryMode& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqStartSentryMode(ReqStartSentryMode&& from) noexcept
    : ReqStartSentryMode() {
    *this = ::std::move(from);
  }

  inline ReqStartSentryMode& operator=(ReqStartSentryMode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqStartSentryMode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqStartSentryMode* internal_default_instance() {
    return reinterpret_cast<const ReqStartSentryMode*>(
               &_ReqStartSentryMode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ReqStartSentryMode* other);
  friend void swap(ReqStartSentryMode& a, ReqStartSentryMode& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqStartSentryMode* New() const final {
    return CreateMaybeMessage<ReqStartSentryMode>(NULL);
  }

  ReqStartSentryMode* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqStartSentryMode>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqStartSentryMode& from);
  void MergeFrom(const ReqStartSentryMode& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqStartSentryMode* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 mode = 1;
  void clear_mode();
  static const int kModeFieldNumber = 1;
  ::google::protobuf::int32 mode() const;
  void set_mode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ReqStartSentryMode)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 mode_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tracking_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqStopSentryMode : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqStopSentryMode) */ {
 public:
  ReqStopSentryMode();
  virtual ~ReqStopSentryMode();

  ReqStopSentryMode(const ReqStopSentryMode& from);

  inline ReqStopSentryMode& operator=(const ReqStopSentryMode& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqStopSentryMode(ReqStopSentryMode&& from) noexcept
    : ReqStopSentryMode() {
    *this = ::std::move(from);
  }

  inline ReqStopSentryMode& operator=(ReqStopSentryMode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqStopSentryMode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqStopSentryMode* internal_default_instance() {
    return reinterpret_cast<const ReqStopSentryMode*>(
               &_ReqStopSentryMode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ReqStopSentryMode* other);
  friend void swap(ReqStopSentryMode& a, ReqStopSentryMode& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqStopSentryMode* New() const final {
    return CreateMaybeMessage<ReqStopSentryMode>(NULL);
  }

  ReqStopSentryMode* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqStopSentryMode>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqStopSentryMode& from);
  void MergeFrom(const ReqStopSentryMode& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqStopSentryMode* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:dwarf.ReqStopSentryMode)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tracking_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqMOTStart : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqMOTStart) */ {
 public:
  ReqMOTStart();
  virtual ~ReqMOTStart();

  ReqMOTStart(const ReqMOTStart& from);

  inline ReqMOTStart& operator=(const ReqMOTStart& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqMOTStart(ReqMOTStart&& from) noexcept
    : ReqMOTStart() {
    *this = ::std::move(from);
  }

  inline ReqMOTStart& operator=(ReqMOTStart&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqMOTStart& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqMOTStart* internal_default_instance() {
    return reinterpret_cast<const ReqMOTStart*>(
               &_ReqMOTStart_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ReqMOTStart* other);
  friend void swap(ReqMOTStart& a, ReqMOTStart& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqMOTStart* New() const final {
    return CreateMaybeMessage<ReqMOTStart>(NULL);
  }

  ReqMOTStart* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqMOTStart>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqMOTStart& from);
  void MergeFrom(const ReqMOTStart& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqMOTStart* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:dwarf.ReqMOTStart)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tracking_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ReqMOTTrackOne : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dwarf.ReqMOTTrackOne) */ {
 public:
  ReqMOTTrackOne();
  virtual ~ReqMOTTrackOne();

  ReqMOTTrackOne(const ReqMOTTrackOne& from);

  inline ReqMOTTrackOne& operator=(const ReqMOTTrackOne& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqMOTTrackOne(ReqMOTTrackOne&& from) noexcept
    : ReqMOTTrackOne() {
    *this = ::std::move(from);
  }

  inline ReqMOTTrackOne& operator=(ReqMOTTrackOne&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqMOTTrackOne& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqMOTTrackOne* internal_default_instance() {
    return reinterpret_cast<const ReqMOTTrackOne*>(
               &_ReqMOTTrackOne_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ReqMOTTrackOne* other);
  friend void swap(ReqMOTTrackOne& a, ReqMOTTrackOne& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqMOTTrackOne* New() const final {
    return CreateMaybeMessage<ReqMOTTrackOne>(NULL);
  }

  ReqMOTTrackOne* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqMOTTrackOne>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqMOTTrackOne& from);
  void MergeFrom(const ReqMOTTrackOne& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqMOTTrackOne* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dwarf.ReqMOTTrackOne)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tracking_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReqStartTrack

// int32 x = 1;
inline void ReqStartTrack::clear_x() {
  x_ = 0;
}
inline ::google::protobuf::int32 ReqStartTrack::x() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqStartTrack.x)
  return x_;
}
inline void ReqStartTrack::set_x(::google::protobuf::int32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqStartTrack.x)
}

// int32 y = 2;
inline void ReqStartTrack::clear_y() {
  y_ = 0;
}
inline ::google::protobuf::int32 ReqStartTrack::y() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqStartTrack.y)
  return y_;
}
inline void ReqStartTrack::set_y(::google::protobuf::int32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqStartTrack.y)
}

// int32 w = 3;
inline void ReqStartTrack::clear_w() {
  w_ = 0;
}
inline ::google::protobuf::int32 ReqStartTrack::w() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqStartTrack.w)
  return w_;
}
inline void ReqStartTrack::set_w(::google::protobuf::int32 value) {
  
  w_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqStartTrack.w)
}

// int32 h = 4;
inline void ReqStartTrack::clear_h() {
  h_ = 0;
}
inline ::google::protobuf::int32 ReqStartTrack::h() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqStartTrack.h)
  return h_;
}
inline void ReqStartTrack::set_h(::google::protobuf::int32 value) {
  
  h_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqStartTrack.h)
}

// -------------------------------------------------------------------

// ReqStopTrack

// -------------------------------------------------------------------

// ReqStartSentryMode

// int32 mode = 1;
inline void ReqStartSentryMode::clear_mode() {
  mode_ = 0;
}
inline ::google::protobuf::int32 ReqStartSentryMode::mode() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqStartSentryMode.mode)
  return mode_;
}
inline void ReqStartSentryMode::set_mode(::google::protobuf::int32 value) {
  
  mode_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqStartSentryMode.mode)
}

// -------------------------------------------------------------------

// ReqStopSentryMode

// -------------------------------------------------------------------

// ReqMOTStart

// -------------------------------------------------------------------

// ReqMOTTrackOne

// int32 id = 1;
inline void ReqMOTTrackOne::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 ReqMOTTrackOne::id() const {
  // @@protoc_insertion_point(field_get:dwarf.ReqMOTTrackOne.id)
  return id_;
}
inline void ReqMOTTrackOne::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:dwarf.ReqMOTTrackOne.id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dwarf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_tracking_2eproto
