// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

#include "tracking.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace dwarf {
class ReqStartTrackDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqStartTrack>
      _instance;
} _ReqStartTrack_default_instance_;
class ReqStopTrackDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqStopTrack>
      _instance;
} _ReqStopTrack_default_instance_;
class ReqStartSentryModeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqStartSentryMode>
      _instance;
} _ReqStartSentryMode_default_instance_;
class ReqStopSentryModeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqStopSentryMode>
      _instance;
} _ReqStopSentryMode_default_instance_;
class ReqMOTStartDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqMOTStart>
      _instance;
} _ReqMOTStart_default_instance_;
class ReqMOTTrackOneDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqMOTTrackOne>
      _instance;
} _ReqMOTTrackOne_default_instance_;
}  // namespace dwarf
namespace protobuf_tracking_2eproto {
static void InitDefaultsReqStartTrack() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqStartTrack_default_instance_;
    new (ptr) ::dwarf::ReqStartTrack();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqStartTrack::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqStartTrack =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqStartTrack}, {}};

static void InitDefaultsReqStopTrack() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqStopTrack_default_instance_;
    new (ptr) ::dwarf::ReqStopTrack();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqStopTrack::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqStopTrack =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqStopTrack}, {}};

static void InitDefaultsReqStartSentryMode() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqStartSentryMode_default_instance_;
    new (ptr) ::dwarf::ReqStartSentryMode();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqStartSentryMode::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqStartSentryMode =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqStartSentryMode}, {}};

static void InitDefaultsReqStopSentryMode() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqStopSentryMode_default_instance_;
    new (ptr) ::dwarf::ReqStopSentryMode();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqStopSentryMode::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqStopSentryMode =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqStopSentryMode}, {}};

static void InitDefaultsReqMOTStart() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqMOTStart_default_instance_;
    new (ptr) ::dwarf::ReqMOTStart();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqMOTStart::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqMOTStart =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqMOTStart}, {}};

static void InitDefaultsReqMOTTrackOne() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dwarf::_ReqMOTTrackOne_default_instance_;
    new (ptr) ::dwarf::ReqMOTTrackOne();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dwarf::ReqMOTTrackOne::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ReqMOTTrackOne =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsReqMOTTrackOne}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ReqStartTrack.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqStopTrack.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqStartSentryMode.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqStopSentryMode.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqMOTStart.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReqMOTTrackOne.base);
}

::google::protobuf::Metadata file_level_metadata[6];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartTrack, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartTrack, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartTrack, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartTrack, w_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartTrack, h_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStopTrack, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartSentryMode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStartSentryMode, mode_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqStopSentryMode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMOTStart, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMOTTrackOne, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dwarf::ReqMOTTrackOne, id_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::dwarf::ReqStartTrack)},
  { 9, -1, sizeof(::dwarf::ReqStopTrack)},
  { 14, -1, sizeof(::dwarf::ReqStartSentryMode)},
  { 20, -1, sizeof(::dwarf::ReqStopSentryMode)},
  { 25, -1, sizeof(::dwarf::ReqMOTStart)},
  { 30, -1, sizeof(::dwarf::ReqMOTTrackOne)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqStartTrack_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqStopTrack_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqStartSentryMode_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqStopSentryMode_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqMOTStart_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dwarf::_ReqMOTTrackOne_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "tracking.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016tracking.proto\022\005dwarf\";\n\rReqStartTrack"
      "\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\t\n\001w\030\003 \001(\005\022\t\n\001h\030\004"
      " \001(\005\"\016\n\014ReqStopTrack\"\"\n\022ReqStartSentryMo"
      "de\022\014\n\004mode\030\001 \001(\005\"\023\n\021ReqStopSentryMode\"\r\n"
      "\013ReqMOTStart\"\034\n\016ReqMOTTrackOne\022\n\n\002id\030\001 \001"
      "(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 210);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tracking.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_tracking_2eproto
namespace dwarf {

// ===================================================================

void ReqStartTrack::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqStartTrack::kXFieldNumber;
const int ReqStartTrack::kYFieldNumber;
const int ReqStartTrack::kWFieldNumber;
const int ReqStartTrack::kHFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqStartTrack::ReqStartTrack()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_tracking_2eproto::scc_info_ReqStartTrack.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqStartTrack)
}
ReqStartTrack::ReqStartTrack(const ReqStartTrack& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&h_) -
    reinterpret_cast<char*>(&x_)) + sizeof(h_));
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqStartTrack)
}

void ReqStartTrack::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&h_) -
      reinterpret_cast<char*>(&x_)) + sizeof(h_));
}

ReqStartTrack::~ReqStartTrack() {
  // @@protoc_insertion_point(destructor:dwarf.ReqStartTrack)
  SharedDtor();
}

void ReqStartTrack::SharedDtor() {
}

void ReqStartTrack::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqStartTrack::descriptor() {
  ::protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqStartTrack& ReqStartTrack::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_tracking_2eproto::scc_info_ReqStartTrack.base);
  return *internal_default_instance();
}


void ReqStartTrack::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqStartTrack)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&h_) -
      reinterpret_cast<char*>(&x_)) + sizeof(h_));
  _internal_metadata_.Clear();
}

bool ReqStartTrack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqStartTrack)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 w = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &w_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 h = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &h_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqStartTrack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqStartTrack)
  return false;
#undef DO_
}

void ReqStartTrack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqStartTrack)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->x(), output);
  }

  // int32 y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->y(), output);
  }

  // int32 w = 3;
  if (this->w() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->w(), output);
  }

  // int32 h = 4;
  if (this->h() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->h(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqStartTrack)
}

::google::protobuf::uint8* ReqStartTrack::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqStartTrack)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->x(), target);
  }

  // int32 y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->y(), target);
  }

  // int32 w = 3;
  if (this->w() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->w(), target);
  }

  // int32 h = 4;
  if (this->h() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->h(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqStartTrack)
  return target;
}

size_t ReqStartTrack::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqStartTrack)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 x = 1;
  if (this->x() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->x());
  }

  // int32 y = 2;
  if (this->y() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->y());
  }

  // int32 w = 3;
  if (this->w() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->w());
  }

  // int32 h = 4;
  if (this->h() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->h());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqStartTrack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqStartTrack)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqStartTrack* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqStartTrack>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqStartTrack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqStartTrack)
    MergeFrom(*source);
  }
}

void ReqStartTrack::MergeFrom(const ReqStartTrack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqStartTrack)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.w() != 0) {
    set_w(from.w());
  }
  if (from.h() != 0) {
    set_h(from.h());
  }
}

void ReqStartTrack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqStartTrack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqStartTrack::CopyFrom(const ReqStartTrack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqStartTrack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqStartTrack::IsInitialized() const {
  return true;
}

void ReqStartTrack::Swap(ReqStartTrack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqStartTrack::InternalSwap(ReqStartTrack* other) {
  using std::swap;
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(w_, other->w_);
  swap(h_, other->h_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqStartTrack::GetMetadata() const {
  protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqStopTrack::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqStopTrack::ReqStopTrack()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_tracking_2eproto::scc_info_ReqStopTrack.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqStopTrack)
}
ReqStopTrack::ReqStopTrack(const ReqStopTrack& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqStopTrack)
}

void ReqStopTrack::SharedCtor() {
}

ReqStopTrack::~ReqStopTrack() {
  // @@protoc_insertion_point(destructor:dwarf.ReqStopTrack)
  SharedDtor();
}

void ReqStopTrack::SharedDtor() {
}

void ReqStopTrack::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqStopTrack::descriptor() {
  ::protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqStopTrack& ReqStopTrack::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_tracking_2eproto::scc_info_ReqStopTrack.base);
  return *internal_default_instance();
}


void ReqStopTrack::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqStopTrack)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool ReqStopTrack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqStopTrack)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqStopTrack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqStopTrack)
  return false;
#undef DO_
}

void ReqStopTrack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqStopTrack)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqStopTrack)
}

::google::protobuf::uint8* ReqStopTrack::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqStopTrack)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqStopTrack)
  return target;
}

size_t ReqStopTrack::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqStopTrack)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqStopTrack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqStopTrack)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqStopTrack* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqStopTrack>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqStopTrack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqStopTrack)
    MergeFrom(*source);
  }
}

void ReqStopTrack::MergeFrom(const ReqStopTrack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqStopTrack)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ReqStopTrack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqStopTrack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqStopTrack::CopyFrom(const ReqStopTrack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqStopTrack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqStopTrack::IsInitialized() const {
  return true;
}

void ReqStopTrack::Swap(ReqStopTrack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqStopTrack::InternalSwap(ReqStopTrack* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqStopTrack::GetMetadata() const {
  protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqStartSentryMode::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqStartSentryMode::kModeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqStartSentryMode::ReqStartSentryMode()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_tracking_2eproto::scc_info_ReqStartSentryMode.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqStartSentryMode)
}
ReqStartSentryMode::ReqStartSentryMode(const ReqStartSentryMode& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  mode_ = from.mode_;
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqStartSentryMode)
}

void ReqStartSentryMode::SharedCtor() {
  mode_ = 0;
}

ReqStartSentryMode::~ReqStartSentryMode() {
  // @@protoc_insertion_point(destructor:dwarf.ReqStartSentryMode)
  SharedDtor();
}

void ReqStartSentryMode::SharedDtor() {
}

void ReqStartSentryMode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqStartSentryMode::descriptor() {
  ::protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqStartSentryMode& ReqStartSentryMode::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_tracking_2eproto::scc_info_ReqStartSentryMode.base);
  return *internal_default_instance();
}


void ReqStartSentryMode::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqStartSentryMode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  mode_ = 0;
  _internal_metadata_.Clear();
}

bool ReqStartSentryMode::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqStartSentryMode)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 mode = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mode_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqStartSentryMode)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqStartSentryMode)
  return false;
#undef DO_
}

void ReqStartSentryMode::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqStartSentryMode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 mode = 1;
  if (this->mode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->mode(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqStartSentryMode)
}

::google::protobuf::uint8* ReqStartSentryMode::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqStartSentryMode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 mode = 1;
  if (this->mode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->mode(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqStartSentryMode)
  return target;
}

size_t ReqStartSentryMode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqStartSentryMode)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 mode = 1;
  if (this->mode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mode());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqStartSentryMode::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqStartSentryMode)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqStartSentryMode* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqStartSentryMode>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqStartSentryMode)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqStartSentryMode)
    MergeFrom(*source);
  }
}

void ReqStartSentryMode::MergeFrom(const ReqStartSentryMode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqStartSentryMode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.mode() != 0) {
    set_mode(from.mode());
  }
}

void ReqStartSentryMode::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqStartSentryMode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqStartSentryMode::CopyFrom(const ReqStartSentryMode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqStartSentryMode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqStartSentryMode::IsInitialized() const {
  return true;
}

void ReqStartSentryMode::Swap(ReqStartSentryMode* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqStartSentryMode::InternalSwap(ReqStartSentryMode* other) {
  using std::swap;
  swap(mode_, other->mode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqStartSentryMode::GetMetadata() const {
  protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqStopSentryMode::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqStopSentryMode::ReqStopSentryMode()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_tracking_2eproto::scc_info_ReqStopSentryMode.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqStopSentryMode)
}
ReqStopSentryMode::ReqStopSentryMode(const ReqStopSentryMode& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqStopSentryMode)
}

void ReqStopSentryMode::SharedCtor() {
}

ReqStopSentryMode::~ReqStopSentryMode() {
  // @@protoc_insertion_point(destructor:dwarf.ReqStopSentryMode)
  SharedDtor();
}

void ReqStopSentryMode::SharedDtor() {
}

void ReqStopSentryMode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqStopSentryMode::descriptor() {
  ::protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqStopSentryMode& ReqStopSentryMode::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_tracking_2eproto::scc_info_ReqStopSentryMode.base);
  return *internal_default_instance();
}


void ReqStopSentryMode::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqStopSentryMode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool ReqStopSentryMode::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqStopSentryMode)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqStopSentryMode)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqStopSentryMode)
  return false;
#undef DO_
}

void ReqStopSentryMode::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqStopSentryMode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqStopSentryMode)
}

::google::protobuf::uint8* ReqStopSentryMode::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqStopSentryMode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqStopSentryMode)
  return target;
}

size_t ReqStopSentryMode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqStopSentryMode)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqStopSentryMode::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqStopSentryMode)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqStopSentryMode* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqStopSentryMode>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqStopSentryMode)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqStopSentryMode)
    MergeFrom(*source);
  }
}

void ReqStopSentryMode::MergeFrom(const ReqStopSentryMode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqStopSentryMode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ReqStopSentryMode::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqStopSentryMode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqStopSentryMode::CopyFrom(const ReqStopSentryMode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqStopSentryMode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqStopSentryMode::IsInitialized() const {
  return true;
}

void ReqStopSentryMode::Swap(ReqStopSentryMode* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqStopSentryMode::InternalSwap(ReqStopSentryMode* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqStopSentryMode::GetMetadata() const {
  protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqMOTStart::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqMOTStart::ReqMOTStart()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_tracking_2eproto::scc_info_ReqMOTStart.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqMOTStart)
}
ReqMOTStart::ReqMOTStart(const ReqMOTStart& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqMOTStart)
}

void ReqMOTStart::SharedCtor() {
}

ReqMOTStart::~ReqMOTStart() {
  // @@protoc_insertion_point(destructor:dwarf.ReqMOTStart)
  SharedDtor();
}

void ReqMOTStart::SharedDtor() {
}

void ReqMOTStart::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqMOTStart::descriptor() {
  ::protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqMOTStart& ReqMOTStart::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_tracking_2eproto::scc_info_ReqMOTStart.base);
  return *internal_default_instance();
}


void ReqMOTStart::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqMOTStart)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool ReqMOTStart::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqMOTStart)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqMOTStart)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqMOTStart)
  return false;
#undef DO_
}

void ReqMOTStart::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqMOTStart)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqMOTStart)
}

::google::protobuf::uint8* ReqMOTStart::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqMOTStart)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqMOTStart)
  return target;
}

size_t ReqMOTStart::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqMOTStart)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqMOTStart::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqMOTStart)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqMOTStart* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqMOTStart>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqMOTStart)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqMOTStart)
    MergeFrom(*source);
  }
}

void ReqMOTStart::MergeFrom(const ReqMOTStart& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqMOTStart)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ReqMOTStart::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqMOTStart)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqMOTStart::CopyFrom(const ReqMOTStart& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqMOTStart)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqMOTStart::IsInitialized() const {
  return true;
}

void ReqMOTStart::Swap(ReqMOTStart* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqMOTStart::InternalSwap(ReqMOTStart* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqMOTStart::GetMetadata() const {
  protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReqMOTTrackOne::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqMOTTrackOne::kIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqMOTTrackOne::ReqMOTTrackOne()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_tracking_2eproto::scc_info_ReqMOTTrackOne.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dwarf.ReqMOTTrackOne)
}
ReqMOTTrackOne::ReqMOTTrackOne(const ReqMOTTrackOne& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:dwarf.ReqMOTTrackOne)
}

void ReqMOTTrackOne::SharedCtor() {
  id_ = 0;
}

ReqMOTTrackOne::~ReqMOTTrackOne() {
  // @@protoc_insertion_point(destructor:dwarf.ReqMOTTrackOne)
  SharedDtor();
}

void ReqMOTTrackOne::SharedDtor() {
}

void ReqMOTTrackOne::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReqMOTTrackOne::descriptor() {
  ::protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqMOTTrackOne& ReqMOTTrackOne::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_tracking_2eproto::scc_info_ReqMOTTrackOne.base);
  return *internal_default_instance();
}


void ReqMOTTrackOne::Clear() {
// @@protoc_insertion_point(message_clear_start:dwarf.ReqMOTTrackOne)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_ = 0;
  _internal_metadata_.Clear();
}

bool ReqMOTTrackOne::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dwarf.ReqMOTTrackOne)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dwarf.ReqMOTTrackOne)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dwarf.ReqMOTTrackOne)
  return false;
#undef DO_
}

void ReqMOTTrackOne::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dwarf.ReqMOTTrackOne)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dwarf.ReqMOTTrackOne)
}

::google::protobuf::uint8* ReqMOTTrackOne::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dwarf.ReqMOTTrackOne)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dwarf.ReqMOTTrackOne)
  return target;
}

size_t ReqMOTTrackOne::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dwarf.ReqMOTTrackOne)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqMOTTrackOne::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dwarf.ReqMOTTrackOne)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqMOTTrackOne* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqMOTTrackOne>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dwarf.ReqMOTTrackOne)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dwarf.ReqMOTTrackOne)
    MergeFrom(*source);
  }
}

void ReqMOTTrackOne::MergeFrom(const ReqMOTTrackOne& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dwarf.ReqMOTTrackOne)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id() != 0) {
    set_id(from.id());
  }
}

void ReqMOTTrackOne::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dwarf.ReqMOTTrackOne)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqMOTTrackOne::CopyFrom(const ReqMOTTrackOne& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dwarf.ReqMOTTrackOne)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqMOTTrackOne::IsInitialized() const {
  return true;
}

void ReqMOTTrackOne::Swap(ReqMOTTrackOne* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqMOTTrackOne::InternalSwap(ReqMOTTrackOne* other) {
  using std::swap;
  swap(id_, other->id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReqMOTTrackOne::GetMetadata() const {
  protobuf_tracking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tracking_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace dwarf
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqStartTrack* Arena::CreateMaybeMessage< ::dwarf::ReqStartTrack >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqStartTrack >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqStopTrack* Arena::CreateMaybeMessage< ::dwarf::ReqStopTrack >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqStopTrack >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqStartSentryMode* Arena::CreateMaybeMessage< ::dwarf::ReqStartSentryMode >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqStartSentryMode >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqStopSentryMode* Arena::CreateMaybeMessage< ::dwarf::ReqStopSentryMode >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqStopSentryMode >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqMOTStart* Arena::CreateMaybeMessage< ::dwarf::ReqMOTStart >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqMOTStart >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dwarf::ReqMOTTrackOne* Arena::CreateMaybeMessage< ::dwarf::ReqMOTTrackOne >(Arena* arena) {
  return Arena::CreateInternal< ::dwarf::ReqMOTTrackOne >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
